### ISSUE TITLE
generic question

### ISSUE THREAD

**Issue by cesalo** [tombowditch/telly#1]
I just found this, thanks a lot. My question is the following (and sorry if the question is too simple or not for you but I'm just getting familiar with all of this):

I have a IPTV service and I'm getting the m3u file through a url using the API of my provider with my user/pass. I see in the m3u a url with a ts file for every channel. My question is do I have to generate this m3u with some frequency?
I'm asking this because in the past I was using a different tvproxy and it automatically generated a token that was changed every 4h by the provider. I don't see this here but just in case.

Thanks again.

**Comment by tombowditch** [comment]
It'd mostly depend on your provider. In my case, nope, so it's probably the same for you!

T

**Comment by cesalo** [comment]
Thanks.
