### ISSUE TITLE
1 Channel showing

### ISSUE THREAD

**Issue by romeoz1323** [tombowditch/telly#10]
I have 9 channles in my m3u file but only 1 is showing up. here is my output. everything seems to be running fine though.

#EXTM3U
#EXTINF:-1, tvg-ID="HGTV.ca" tvg-name="HGTV CA HD" tvg-logo="http://xxxx.tv/logos/hgtv%20ca%20hd.png" group-title="Canada",HGTV CA HD
http://xxxx.tv:80/live/xxxx/xxxx/2860.ts
#EXTINF:-1, tvg-ID="" tvg-name="Showcase HD" tvg-logo="" group-title="Canada",Showcase HD
http://xxxx.tv:80/live/xxxx/xxxx/75897.ts
#EXTINF:-1, tvg-ID="" tvg-name="Global TV Montreal" tvg-logo="" group-title="Canada",Global TV Montreal
http://xxxx.tv:80/live/xxxx/xxxx/75898.ts
#EXTINF:-1, tvg-ID="ABC.us" tvg-name="ABC HD" tvg-logo="http://xxxx.tv/logos/usa%20abc%20hd.png" group-title="United States",ABC HD
http://xxxx.tv:80/live/xxxx/xxxx/2435.ts
#EXTINF:-1, tvg-ID="CBS.us" tvg-name="CBS HD" tvg-logo="http://xxxx.tv/logos/usa%20cbs%20hd.png" group-title="United States",CBS HD
http://xxxx.tv:80/live/xxxx/xxxx/2440.ts
#EXTINF:-1, tvg-ID="NBC.us" tvg-name="NBC HD" tvg-logo="http://xxxx.tv/logos/usa%20nbc%20hd.png" group-title="United States",NBC HD
http://xxxx.tv:80/live/xxxx/xxxx/2455.ts
#EXTINF:-1, tvg-ID="FOX.us" tvg-name="FOX HD" tvg-logo="http://xxxx.tv/logos/usa%20fox%20hd.png" group-title="United States",FOX HD
http://xxxx.tv:80/live/xxxx/xxxx/2448.ts
#EXTINF:-1, tvg-ID="CW.us" tvg-name="CW HD" tvg-logo="http://xxxx.tv/logos/usa%20cw%20hd.png" group-title="United States",CW HD
http://xxxx.tv:80/live/xxxx/xxxx/8198.ts
#EXTINF:-1, tvg-ID="AandE.us" tvg-name="A&E HD" tvg-logo="http://xxxx.tv/logos/usa%20a%26e%20hd%20.png" group-title="United States",A&E HD
http://xxxx.tv:80/live/xxxx/xxxx/2463.ts

**Comment by tombowditch** [comment]
Can you paste the initial output from telly?

T

**Comment by tombowditch** [comment]
@romeoz1323 see above please ;-)

**Comment by tombowditch** [comment]
Closing this as no reply, please reopen if you're replying.
