### ISSUE TITLE
Installing on a Raspberry Pi using HypriotOS and Docker

### ISSUE THREAD

**Issue by TonyTheTechie** [tombowditch/telly#100]
I am trying to install Telly in a Docker Container on a Raspberry Pi 3 installed with HypriotOS.
I have managed to Pull the container, but I can't see how to proceed after that.
I have searched the web for some guidance, but have found none. Are there any more detailed instructions for installing in this environment .

Thanks

Tony Self

**Comment by HazCod** [comment]
Telly will need the docker `--name telly`, `-listen=0.0.0.0:6077`, `-baseurl=telly:6077`, `-temp=/tmp` and `-playlist=http://url-to-your-playlist.m3u` arguments.

e.g. `docker run -ti --name=telly tombowditch/telly -listen=0.0.0.0:6077 -baseurl=telly:6077 -temp=/tmp -playlist=http://url-to-playlist.m3u`

Note: We're currently in the process of releasing so it's possible the image with `-baseurl` isn't live just yet. (I added baseurl for Docker support)

**Comment by TonyTheTechie** [comment]
Thanks HazCod. I just tried the above line and got the following error: standard_init_linux.go:190: exec user process caused "exec format error"

**Comment by HazCod** [comment]
What is the syntax of your `CMD` invocation @TonyTheTechie ?

**Comment by TonyTheTechie** [comment]
HazCod sorry for the delay in replying. I have given up on the docker installation for the moment and have gone back to a basic Raspbian install. I have got Plex installed and Telly and have configured Plex's PVR, but I am not having much success with the IPTV feeds. I am using the UK iptvsource.com lists, but they seem update these everyday and they don't seem very stable. Can someone recommend m3u playlist I can use in the UK to test out my setup. Don't really care what channels it includes as long as the streams are stable and will prove that my hardware setup can handle a live feed and record a few test programmes. I would like multiple channels so I can see how many virtual tuners it can support.
