### ISSUE TITLE
Plex dont find telly Docker Install Ubuntu

### ISSUE THREAD

**Issue by Oggymator** [tombowditch/telly#101]
Hi,

I installed as Docker on Ubuntu with this command:
_sudo docker run -ti -p 6077:6077 --name=telly tomboitch/telly -listen=0.0.0.0:6077 -temp=/tmp -playlist=http://www_

If I open the IP of ubuntu:6077 I got this message:
`<root><specVersion><major>1</major><minor>0</minor></specVersion><URLBase>http://0.0.0.0:6077</URLBase><device><deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType><friendlyName>telly</friendlyName><manufacturer>Silicondust</manufacturer><modelName>HDHR-2US</modelName><modelNumber>HDHR-2US</modelNumber><serialNumber/><UDN>uuid:12345678</UDN></device></root>`

If I use this IP and Port on Plex DVR nothing happend.
Any Idea what I did wrong?

Plex runs on a different machine and not in a Docker.

EDIT: if I run IP of ubuntu:6077/lineup.json
I see all the channels.
Seems telly works well?!

EDIT2:
I changed the uuid/deviceid and Plex found it.
But only for few seconds and then it is gone.
Every time I change the uuid, I found it only for few seconds.

EDIT3:
I can get only telly 0.5 for docker, not newest version 0.6

thanks
Tobias

**Comment by Oggymator** [comment]
Can somebody psuh 0.6 telly to docker hub?
Dockerfile report an error.
Maybe 0.6 solve my problems, find no solution on the internet

**Comment by Oggymator** [comment]
fiend the problem.
seems to be a problem with the friendly name.

But now I have next problem.
Plex find channels and I set channels and EPG, but now it is endless loading. I cannot finish it...

**Comment by HazCod** [comment]
What did you change in the friendly name to make it work? What didn't work?
Give us some details so we can help other people.

**Comment by Oggymator** [comment]
Change friendly name to "HDHomerun" like you discussed here:
https://github.com/tombowditch/telly/pull/48

Now Plex find it and also the channels.
On EPG screen is endless loading.
![plex-epg](https://user-images.githubusercontent.com/1413794/40786646-d2e8c918-64eb-11e8-9ace-73203d92be2b.JPG)

**Comment by HazCod** [comment]
Ahh, that's fixed in version 0.6 which is not on Docker Hub yet.
The duration of the loading is because Plex has difficulties working with that amount of channels.

**Comment by Oggymator** [comment]
I have 122 channels but marked only 1 for testing.
Do you mean I have to wait longer?
Can you push the build for Docker Hub or activate autobuild?
thanks :)

**Comment by HazCod** [comment]
For Docker Hub, we're keeping track of the issues here; https://github.com/tombowditch/telly/issues/99
