### ISSUE TITLE
Unable to read M3U file

### ISSUE THREAD

**Issue by crowirl** [tombowditch/telly#104]
Hi there, so fairly new to this,installing telly on Ubuntu 18.04 64 bit, using telly-linux-386.bin
I run the following command:
`iain@ubuntu:~/Downloads$ sudo '/home/iain/Downloads/telly-linux-386' -playlist=/home/iain/downloads/flawless.m3u
[telly] [info] booting telly v0.5
[telly] [info] Reading m3u file /home/iain/downloads/flawless.m3u...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
	/Users/tom/code/telly/main.go:193 +0x1669
`
However my m3u seems to be in the correct format - see sample below. Can anyone help? PLease :)

`﻿#EXTM3U
#EXTINF:-1 tvg-ID="BBC ONE FHD" tvg-name="UK: BBC ONE FHD" tvg-logo="https://archive.org/download/stevechatfield27_gmail_Bbc1/bbc%201.png" group-title="UK: Entertainment",UK: BBC ONE FHD
http://pp.flawless-hosting.solutions:80/live/XXXXXX@XXXXX.com/XXXXXXXXXXXXX/8015.ts`

**Comment by LennyM8472** [comment]
same here

**Comment by shaneosullivanky** [comment]
I didn’t want to post anything in case I was doing something wrong but my .M3U file was working perfectly up to I think version V0.4.4 and on the next update I was getting an error saying the M3U was not in the correct format. Nothing had changed with my playlist file. I’ve read several comments about it needing to be in Unicode 8 and M3U8 format, I’ve spent days trying different things but it still won’t recognise the file.

So I am a Same Here as well.

**Comment by HazCod** [comment]
@tombowditch , any ideas? Sounds phishy

**Comment by crowirl** [comment]
Never mind I managed to get it working by changing the m3u layout from this 
﻿#EXTM3U #EXTINF:-1 tvg-ID="BBC ONE FHD" tvg-name="UK: BBC ONE FHD" tvg-logo="https://archive.org/download/stevechatfield27_gmail_Bbc1/bbc%201.png" group-title="UK: Entertainment",UK: BBC ONE FHD http://pp.flawless-hosting.solutions:80/live/XXXXXX@XXXXX.com/XXXXXXXXXXXXX/8015.ts

To this 
﻿#EXTM3U #EXTINF:-0, BBC ONE FHD http://pp.flawless-hosting.solutions:80/live/XXXXXX@XXXXX.com/XXXXXXXXXXXXX/8015.ts

**Comment by shaneosullivanky** [comment]
Excellent, thank you for this. For months I’ve given up on using telly and your post resolved all my issues.

Tom would it be a good idea to post this in the readme for a good format for the m3u file?
