### ISSUE TITLE
Plex GRID Column Overlap with IPTV XML

### ISSUE THREAD

**Issue by nroTTron** [tombowditch/telly#111]
There is compatibility issue with IPTV EPG URL & Plex Grid. The Plex Grid looks for channel number + channel icon. However, IPTV EPGs load channel name + channel icons into the Plex grid. This causes the first two columns of the grid to overlap.

Here is a snippet from IPTV M3u:

**#EXTINF:-1 tvg-id="US: A&E" tvg-name="US: A&E" tvg-logo="http://IPTVDOMAIN/guide/logos/AE.png" group-title="USA",US: A&E http://IPTVDOMAIN:PORT/live/xxxx/xxxxx/30.ts**

[https://cdn.discordapp.com/attachments/414169930544578562/456215938015166474/unknown.png](url)

**Comment by smromain** [comment]
So, I think this actually just an issue with the EPG data than telly itself.

The plex grid view takes the ID that comes through as a channel number, as you say, but since EPG data doesn't come through telly, I don't think there's anything that can be done now to fix that sort of thing?

**Comment by tombowditch** [comment]
In Stylish I've added..


```
div[class^="ChannelsGridRowTitle-number"] {
    overflow: hidden;
    max-width: 70px;
    min-width: 70px;
}
```

( Thanks to @OmgImAlexis )

**Comment by nroTTron** [comment]
@tombowditch - What file/path is this entry made or modified?

**Comment by Codehhh** [comment]
@nroTTron Stylish is this: [Stylish @ Chrome Web Store](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en)

**Comment by tombowditch** [comment]
I've applied it for whole of app.plex.tv

**Comment by BDS369** [comment]
@tombowditch would you mind posting a link to your stylish skin? 
Would love to try it

**Comment by smromain** [comment]
It seems like Plex's latest updates (1.13.3.5223) have actually fixed this natively. This isn't a documented fix in their release notes but I've tried it in a few different browsers and seems to be the case all around.

![screen shot 2018-07-05 at 9 36 57 am](https://user-images.githubusercontent.com/3893316/42329718-01d8b830-8037-11e8-9928-79a2f6a5d5e0.png)

**Comment by HazCod** [comment]
Yay!
