### ISSUE TITLE
DVR Device name is tvhProxy, not telly

### ISSUE THREAD

**Issue by emreuenal** [tombowditch/telly#12]
Thank your for this great project.

I have some trouble to get it work.

If i try to add telly to the plex, i am getting this:

![telly](https://user-images.githubusercontent.com/6360198/36073998-dd140dba-0f39-11e8-85c1-2368611adfc4.png)

If i am done with the configuration, cant open any channel (unable to tune channel, timed out).

On the DVR settings from plex:

![image](https://user-images.githubusercontent.com/6360198/36074058-cce46006-0f3a-11e8-9e9f-c1a41bae5ca5.png)
 
I am not using tvhproxy or tvheadend.

**Comment by tombowditch** [comment]
Did you try using tvhProxy before telly? Plex has this weird issue where it grabs the old name.

**Comment by tombowditch** [comment]
> If i try to add telly to the plex, i am getting this:

Can you paste the output of telly here please?

**Comment by emreuenal** [comment]
> Did you try using tvhProxy before telly?

Yes, that was long time ago

> Can you paste the output of telly here please?

```
$./telly-linux-amd64 -file=/app/telly/cha.m3u
[telly] [parser] Reading m3u file /app/telly/cha.m3u ...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 1 channels

[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] listening on localhost:6077
```

with logrequests:

```
$./telly-linux-amd64 -logrequests -file=/app/telly/cha.m3u
[telly] [parser] Reading m3u file /app/telly/cha.m3u ...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 1 channels

[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] listening on localhost:6077
[telly] [request] /lineup.json
[telly] [request] /discover.json
[telly] [request] /lineup_status.json
[telly] [request] /discover.json
[telly] [request] /lineup_status.json
[telly] [request] /lineup.json
[telly] [request] /lineup.json
```

Thank you...

**Comment by emreuenal** [comment]
Restarted PMS a couple of times and the issue is gone.

**Comment by tombowditch** [comment]
Figured, Plex gets a bit weird.

Shall I close this now?

**Comment by emreuenal** [comment]
Yes we can close the issue.

For all with the same problem, stop and start PMS again while telly running in background.
