### ISSUE TITLE
Error opening URL playlist on Windows 10 x64

### ISSUE THREAD

**Issue by MikelillOi** [tombowditch/telly#120]
Hi. If I execute this command, everything works fine. With the .m3u downloaded

telly-windows-amd64.exe -playlist=tv_channels_nanox5_plus.m3u -useregex "ES:"

But if I change for the URL I have always the error below.
telly-windows-amd64.exe -playlist=http://xxxxx.com/tv_channels_nanox5_plus.m3u -useregex "ES:"
[telly] [error] Could not create file: C:\Users\MIKELI~1\AppData\Local\Temp ; open C:\Users\MIKELI~1\AppData\Local\Temp: is a directory

There is any solution?

Regards

**Comment by mediaman88** [comment]
Same here, there was another thread on it that said solved but I don't see the solution, maybe I'm just dense.  I tried creating a blank .m3u file in the temp directory with the right header and in the right UT8 format but then it say it gets a file it wasn't expecting, or can't read it.

I am using Vader Streams and ended up just downloading the file as an M3U, which works, but is not an optimal solution.

**Comment by HazCod** [comment]
Try manually specifying the temp path, e.g. `-temp=C:/m3u`

**Comment by mediaman88** [comment]
Thanks HazCod, someone mentioned that in a previous thread.  Tried it and got a new error.

[telly] [error] unable to read m3u file, error below
panic: Invalid m3u file format. Expected #EXTM3U file header

To clarify should the file already exist where I point it?  if so should it be a blank m3u file with the proper header, or should it be the m3u file I downloaded from the provider?  I've tried all three ways 1. With no file existing the the temp directory, with a blank file existing in the temp directory and with the full m3u file existing in the temp directory, I get the same error above any way I do it.

**Comment by HazCod** [comment]
`-temp` shouldn't be necessary if you specify the file location of the playlist instead of the URL.

**Comment by mediaman88** [comment]
Thanks HazCod, didn't know if there was a benefit of having the URL vs the actual file.

**Comment by HazCod** [comment]
So does it work now? If telly complains about the format, see whether the playlist downloaded is correct.

**Comment by mediaman88** [comment]
Yes, sorry for not responding.  All seems well right now.  Thank you
