### ISSUE TITLE
Can't select tuner type on Plex

### ISSUE THREAD

**Issue by giopas** [tombowditch/telly#123]
I am trying to link my Vu+ (with Black Hole installed) channels on Plex via Telly.

I easily extracted the related .mp3u8 playlist from OpenWebIf (the webinterface of enigma2 os) and given to Telly.

Plex immediately finds the new tuner ("Silicondust HDHomerun (telly)") and immediately shows all channels.

However I only have the option to select the Country but not the Connection type as I can only see "Cable".

If my memory serves me well, in the past I could also select "Satellite", but I cannot see it now.

Is that a Telly related problem or a Plex one (I am running the latest beta version: v. 1.13.3.5223)?

Does this affect the fact that after that Plex cannot find any EPG information?

Thanks

**Comment by hthighway** [comment]
As telly emulates an HDHR device, plex automatically gives you just cable as a choice.  Just click continue and on the next screen provide it with you xmltv link/file

**Comment by giopas** [comment]
Ok, thanks.

Now the problem is to make EPG collection working as - despite the fact the bouquet is liste here [1] - Plex does not recognize it...

[1] https://www.plex.tv/live-tv-dvr/
