### ISSUE TITLE
Multiple instances?

### ISSUE THREAD

**Issue by MichealX64** [tombowditch/telly#125]
Hey guys, just set up your telly proxy this morning and it is working beautifully! Super easy to set up, it's exactly what I was looking for!

One question though, is it possible to have multiple instances of Telly on the same host?

From what I can gather, when Plex asks you to match the streams with the channel guide, if you use "Sky HD" as you suggested, any UK Free-to-Air channels are excluded from the list.

So I would like to have 3 instances running:
One for Sky HD channels
One for UK Free-to-Air
One for US Cable

I will be creating and modifying my m3u playlist to match the selected region.

**Comment by MichealX64** [comment]
Looks like multiple instances run no problem, as long as the port number is different obviously.

But the next issue I am running into is the Device-ID.

Starting a second instance causes Plex to get confused and apply the Program Guide from the previous proxy. 
For example: Sky HD is applied and I cannot change it. 
It also forgets the first instance and automatically starts using the second one.

If there was a startup option where we can manually set the device ID this would be great.
Example: `-deviceid=12345678-AE2A-4E54-BBC9-33AF7D5D6A93`

Thanks guys!

**Comment by MichealX64** [comment]
Wow I'm really answering all of my own questions here! Looking forward to a WiKi! Ha

Got it working, I was inserting the whole string similar to my previous comment.
Works after I just use `-deviceid 12345677`

I still have the issue where I cannot change the region, but I think that is a Plex issue. 

Thanks again guys for your awesome work!

**Comment by Deanosim** [comment]
I'm having the exact same problem, I've been trying to change the device ID in the config file but it just makes no difference plex gets confused and tries to use data from the first telly instance.
