### ISSUE TITLE
Any good working examples and explaination

### ISSUE THREAD

**Issue by Foebik** [tombowditch/telly#128]
I've been using useregex and was able to narrow down 4000+ channels to 125 with this. 

`-useregex  .*US`

But it is missing a few channels that I wanted to add. How can I add additional arguments to the regex?

When I try different variations like below, I just end up with 0 channels.

```
-useregex  .*US|.MSNBC.us
-useregex  .*US, .MSNBC.us
-useregex  .*US .MSNBC.us
```

Also when I use `.MSNBC.us` on it's own, it works. Just showing 1 channel. I just dont know how to merge the 2.

**Comment by HazCod** [comment]
Try `-useregex US|MSNBC`

**Comment by Foebik** [comment]
When I try your suggestion, I get this error.

```
 -useregex -useregex US|MSNBC
'MSNBC' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Foebik** [comment]
When I tried your suggestion I get the following error.


```
 -useregex US|MSNBC
'MSNBC' is not recognized as an internal or external command,
operable program or batch file.
```
