### ISSUE TITLE
Need help installing telly on raspbian

### ISSUE THREAD

**Issue by Leolamlao** [tombowditch/telly#129]
I've heard that telly can be used as an iptv plugin for raspbian. I already have plex media server set up and was wondering if you could help me install telly on raspbian. I was looking at the download link and couldn't seem to find the download link for raspbian Linux version.

**Comment by Leolamlao** [comment]
How did you set yours up?

**Comment by HazCod** [comment]
Isn't this what you want? https://github.com/tombowditch/telly/releases/download/v0.6.2/telly-linux-arm64

**Comment by Leolamlao** [comment]
Do you have the instructions to install it if I'm not using docker?

**Comment by HazCod** [comment]
Just download it to your system, make it exectuble and execute it like any other linux command.
e.g.

```
curl -o telly https://github.com/tombowditch/telly/releases/download/v0.6.2/telly-linux-arm5
chmod +x telly
./telly
```

**Comment by Leolamlao** [comment]
Hey HazCod, I ran your command then ran sudo apt-get install telly but it did not seem to work. I am pretty new to Linux,  so sorry for all the stupid questions I asked.

**Comment by chazlarson** [comment]
There's no "install" for telly in the ```apt-get install``` sense
```
curl -Lo telly https://github.com/tombowditch/telly/releases/download/v0.6.2/telly-linux-arm5
```
That downloaded the built telly binary into a local file called "telly"

```
chmod +x telly
```
That set the downloaded file to be executable.

```
./telly
```
That executes the thing to show that it worked.

You can run it from there, or you can move/copy it to somewhere in your $PATH and then you'll be able to type "telly" anywhere just like today you can type "mv" or "cp" or what have you.

**Comment by Leolamlao** [comment]
./telly -playlist=http://........m3u_plus should also work, correct?

**Comment by chazlarson** [comment]
I'm not sure what you're asking.  

If you type that in the directory where you ran the commands up above, that will start telly, yes.  If you type that in any other directory it won't.

That's part of a correct telly invocation, yes, but there are other flags you should set to actually work with telly.  That stuff is outside the scope of this case, though.

**Comment by Leolamlao** [comment]
OK I figured it out. So ya it does work with url. Thank you

**Comment by Leolamlao** [comment]
Is there a way to filter the channel to just us and CA only? - uktv works for UK only but I only want US and CA.

**Comment by Leolamlao** [comment]
Thanks, that works.
