### ISSUE TITLE
Plex in docker can not see telly

### ISSUE THREAD

**Issue by Dec64** [tombowditch/telly#13]
I'm running plex in docker via cloudbox (https://github.com/Cloudbox/Cloudbox).

Running telly locally not in docker works to the point it says go to localhost:6077 but plex says There was a problem adding the device: localhost:6077.

I then put telly into a docker container and have it on the same network as plex docker, same problem works, finds m3u file and says There was a problem adding the device: localhost:6077.

Stuck as what to trouble shoot now.

Tried localhost 0.0.0.0, 127.0.0.1, 172.17.0.15 ect

**Comment by Dec64** [comment]
that's what i thought, but i've tried the IP of the server aswell as the IP's listed by the network on portainer.

172.17.0.15 and 172.17.0.14 still nothing

**Comment by HazCod** [comment]
As discussed in my pull request;  Plex should be started with a --link telly and it should reach http://telly:6077 just fine.

**Comment by animaonline** [comment]
Link has been deprecated, is there any other way to make them work together?

**Comment by chazlarson** [comment]
What link has been deprecated?  In cloudbox, referring to the container by name is still the right answer; there are a couple of cloudbox roles for a couple different releases of telly.

**Comment by animaonline** [comment]
The --link argument has been deprecated. Anyways, I've solved the problem by running both containers on my host's network.

**Comment by chazlarson** [comment]
Oh, I see.  Yes, that param has gone away in recent releases, but there are a few ways to do what you need here.  You've found one; in cloudbox, all the containers run on the same named network and you can refer to them by name rather than IP in config files and so forth.
