### ISSUE TITLE
Installation on win 7

### ISSUE THREAD

**Issue by mattejm31** [tombowditch/telly#132]
Hi. I'm new to this but then again even more grateful for help.

I'm having trouble installing v0.6.2 on my amd 64
The installation just never start and I can't run Telly.

Any ideas on what I'm doing wrong? Fumbling in the dark here at the moment... 

thanks

**Comment by chazlarson** [comment]
What are you calling "the installation"?  All you should have to do is download the executable file and run it directly.

So you'd download one of these:
telly-windows-386.exe
telly-windows-amd64.exe

Then put it wherever you want, open a cmd window, cd to wherever you put it, and run it.

If you're downloading that file then double-clicking it expecting it to install something, it would just open and close.  There isn't an installation in that sense.

**Comment by mattejm31** [comment]
Thanks!
