### ISSUE TITLE
Restream

### ISSUE THREAD

**Issue by 12nick12** [tombowditch/telly#136]
I'm not sure if plex does this automatically, but if it doesn't is there any way to implement it. That way if I'm watching the same channel twice it only uses one stream.

**Comment by porkie02** [comment]
Plex does this already, you can have 10 people watch the same channel but it will only count as one stream to the iptv provider so I have been told.

**Comment by 12nick12** [comment]
Well that's pretty awesome. Thanks for the info.

**Comment by HazCod** [comment]
This is done by Plex btw, nothing to do with telly.
We just pass along the URLs.

**Comment by jaylex32** [comment]
HazCod any new updates coming soon? Thanks

**Comment by HazCod** [comment]
Better to ask on Discord, but last time I checked @tombowditch wanted to do a major overhaul.
