### ISSUE TITLE
Help with -file

### ISSUE THREAD

**Issue by jonbigtelly** [tombowditch/telly#14]
Have downloaded the telly file onto my Mac and using this command to try and run Telly
pointed at my m3u file but it says 'no such file or directory'
Am not great with Command Line any ideas please ? here is the command I am using
chmod +x ./telly -file=/Users/user/Desktop/myiptv.m3u

I have used CD to the file where telly is sitting and it now only gives me that error. Any help would be appreciated.

Jon

**Comment by tombowditch** [comment]
You're trying to combine two commands into one! ;-)

Use this: `chmod +x telly` to make it executable

Then you can run telly: `./telly -file /Users/user/Desktop/myiptv.m3u`

T

**Comment by jonbigtelly** [comment]
Worked straight away thx vm mate
