### ISSUE TITLE
Changes to m3u not picked up by Telly

### ISSUE THREAD

**Issue by taylor-verys** [tombowditch/telly#17]
Once you get Telly setup and running, it does not ever look to re-parse your input `.m3u` file. This could be done either by listening for changes on the file itself, or just allowing the user to set Telly to re-parse the m3u file on a set interval.

In my situation something like this is useful when my provider decides to add channels for live events, or if the URL of a channel changes.

Appreciate the hard work!

**Comment by tombowditch** [comment]
Seems like a good thing to add! Quick bit of research for someone though, I don't believe Plex picks up lineup changes because you need to manually add the channels - can someone confirm that? (If so we need a warning somewhere)

**Comment by cesalo** [comment]
@tombowditch correct .. also it may screwed the EPG if some of the channels are shifted due to new channels being added.

**Comment by HazCod** [comment]
In that case, do we really want to pick up changes automatically?

**Comment by tombowditch** [comment]
Deciding against this because you'd need to rescan Plex anyway. Someone feel free to put in a PR for it, though.
