### ISSUE TITLE
Running sed on OSX produces an error

### ISSUE THREAD

**Issue by taylor-verys** [tombowditch/telly#18]
Running `sed` as instructed in the readme...
`sed -i 's/#EXTINF:-1/#EXTINF:-1,/g' myiptv.m3u`
...on OSX will result in the following error
`sed: 1: "myiptv.m3u": invalid command code o`

OSX requires an additional parameter to run correctly

> The OS X version needs a value for the -i flag so you don’t inadvertently overwrite a file if you don’t mean to. To overwrite the file we’re trying to modify you just need to add two speech marks after the -i flag as follows.
https://ed.gs/2016/01/26/os-x-sed-invalid-command-code/

The following works like a charm
`sed -i "" 's/#EXTINF:-1/#EXTINF:-1,/g' myiptv.m3u`

👍

**Comment by HazCod** [comment]
@tombowditch close this

**Comment by tombowditch** [comment]
@HazCod thanks
