### ISSUE TITLE
nas install

### ISSUE THREAD

**Issue by foXaCe** [tombowditch/telly#19]
Hello, please how to execute on synology nas docker please

**Comment by HazCod** [comment]
Hi, the maintainer is working to make the image `tombowditch/telly` available on Docker Hub, so you can just pull it in.

**Comment by tombowditch** [comment]
Hi, now available in Docker hub. Please see https://hub.docker.com/r/tombowditch/telly/ !

**Comment by foXaCe** [comment]
@tombowditch thank for your job but do not work on my nas

**Comment by tombowditch** [comment]
Have any error messages? Logs? Anything to help?

**Comment by tombowditch** [comment]
Closing this due to lack of reply, feel free to re-open.
