### ISSUE TITLE
How to use -useregex and Examples

### ISSUE THREAD

**Issue by cesalo** [tombowditch/telly#2]
I tried with:
./telly-linux-amd64 -file=xxx.m3u -useregex Latino
and
./telly-linux-amd64 -file=vader.m3u -useregex=Latino
and
./telly-linux-amd64 -file=vader.m3u -useregex=(Latino)

Can you please provide some examples? I'm trying to filter the group "Latino" and "United States" similar to the -uktv flag but for other groups of channels.

I have almost 1200 channels in the playlist and I'm having issues when trying to edit my channel list / mapping in Plex. During setup it loaded ok but afterwards the browser just hangs and then shows an error that was not able to load the list and I see a timeout error in the Plex logs. Not sure if is telly related or Plex related but having a small group of channels I hope it can be fixed.

Thanks.

**Comment by tombowditch** [comment]
@cesalo  `-useregex` is currently just [https://github.com/tombowditch/telly/blob/master/main.go#L81-L82](a couple hardcoded values) which is bad and I should update this.

What do you think - `-useregex <your regex here>` or something like that? I'll get this done for tomorrow if you wish!

**Comment by cesalo** [comment]
Yes .. that would be great. Thanks a lot.

**Comment by tombowditch** [comment]
@cesalo what version are you running? linux amd64? I'll build a possible solution for you

**Comment by cesalo** [comment]
Yes .. Linux amd64 .. thanks.

**Comment by tombowditch** [comment]
@cesalo please try [this](https://github.com/tombowditch/telly/releases/tag/v0.2)

like this: `./telly -useregex <your regex>`

-------------------

> During setup it loaded ok but afterwards the browser just hangs and then shows an error that was not able to load the list and I see a timeout error in the Plex logs.

Same experience here - Plex doesn't like too many channels.

**Comment by cesalo** [comment]
Working like a charm:

`./telly-linux-amd64 -logrequests -useregex 'Latino|United States|Premium Movies|Sports|United Kingdom' -file playlist.m3u`

Thanks.

**Comment by tombowditch** [comment]
Great, thanks. I'll push a proper release shortly.
