### ISSUE TITLE
Vaderstreams m3u

### ISSUE THREAD

**Issue by porkie02** [tombowditch/telly#22]
Has anyone had any luck getting this to work with the vaderstreams m3u? I Have saved the link from them to a m3u file and changed the format. But another thing I noticed by teseting one stream is that telly would only see it if I removed the line tvg-id="BTSport3.uk" for example, this is to much work to remove all of those from a list of about 2000 streams.

#EXTINF:-1, tvg-name="BBC One HD" tvg-id="BBC1.uk" tvg-logo="http://redacted/logos/bbc%20one%20hd.png" group-title="United Kingdom",BBC One HD http://redacted/live/xxxx/xxxx/2464.ts

This line will not work with telly, but if I edit to.

#EXTINF:-1, tvg-name="BBC One HD" tvg-logo="http://redacted/logos/bbc%20one%20hd.png" group-title="United Kingdom",BBC One HD http://redacted/live/xxxx/xxxx/2464.ts

it works

**Comment by cesalo** [comment]
I have a similar playlist and it works. In my case every channel has 2 lines:
#EXTINF:-1, tvg-name="BBC One HD" tvg-id="BBC1.uk" tvg-logo="http://vaders.tv/logos/bbc%20one%20hd.png" group-title="United Kingdom",BBC One HD
http://vaders.tv/live/xxxxx/xxxxx/2464.ts
Difficult to say if in you case is just 1 line or 2 lines (looks like 1 line not sure if that's what is causing the issue). In my case the second line is the one that start with http.

**Comment by EnorMOZ** [comment]
No issues here, however as @cesalo mentioned it is 2 lines

**Comment by 12nick12** [comment]
For mine to work I went into the document and replace every instance of "#EXTINF:-1 " with "#EXTINF:-1, " and that made it work for me.

**Comment by tombowditch** [comment]
Correct @12nick12 - the sed command in the README does this.

@porkie02 i'll be looking into this later today

**Comment by 12nick12** [comment]
Oh OK. I haven't read the readme so I didn't realize it's right there lol.

**Comment by tombowditch** [comment]
I believe this can be closed. Looked at it with @porkie02 and the m3u was on one big line. Apparently the provider has a new m3u and this forks flawlessly (`[telly] [info] found 9655 channels`)

@porkie02 please confirm ;-) 

T

**Comment by porkie02** [comment]
yeah its working now with the new format they give from their standard m3u.

https://i.imgur.com/Kc1Inp2.png

Thanks Tom can close this now I guess
