### ISSUE TITLE
Plex will lose connection to telly, but no error reported

### ISSUE THREAD

**Issue by sfunk1x** [tombowditch/telly#23]
I'm not exactly sure where the break is occurring, but when updating large EPGs (~2500 channels) plex will lose connection to telly and stop the update process. I've never actually gotten it to successfully update the EPG once telly is added. I have another tuner on the network (hdhomerun connect) and plex isn't losing connection to that.

I'm running telly on the same instance as plex, listening on localhost.

**Comment by tombowditch** [comment]
Do you have 2500 channels on your HDHomerun Connect? :-)

I've found Plex just hates alot of EPG data and it crashes on me too - thats why we have -useregex, -uktv, etc.

T

**Comment by sfunk1x** [comment]
Nope, maybe 30 or 40. Plex could absolutely be the culprit here, especially since telly doesn't seem to be crashing (at least nothing is showing up in the screen session I currently have it running in).

**Comment by tombowditch** [comment]
Yep, telly won't be at fault here. All telly gives Plex is the "lineup" which is generates before it even starts listening on the port so it's already all ready. Try filtering it down using the regex and let me know the results.

**Comment by tombowditch** [comment]
documentation update: telly should warn users over X amount of channels

**Comment by tombowditch** [comment]
fixed in 66a4608804c7ec27b5b850e75ff877bee2174cf3
