### ISSUE TITLE
Filters (Options) By Channel #, By Channel Name instead of Group Ttitle?

### ISSUE THREAD

**Issue by s-j-daniels** [tombowditch/telly#236]
I installed Telly and Plex Media Server on an Open Media Vault server in my basement. Everything is working, but I really need to understand the Filters options available in the config file.

My IPTV has 20,000 channels and over 100 groups. I was restricted by the Plex error on Telly for the "480" limitation. I filtered by "USA LOCALS". Problem is when I actually program Plex and select the channels I watch from within that group, 4 channels appear in Plex. If I add any other groups it is immediately cut because of the "limitation" error.

Is there a way to filter by channel. I basically just need a handful of channels so I can record, but they are scattered throughout various groups.

Also... FYI - Kudos on an ingenious backend for Plex.

**Comment by chazlarson** [comment]
Have you read the filtering article in the wiki?

https://github.com/tellytv/telly/wiki/Running-Telly%3A-Filtering

I feel like I've covered it pretty well in there, but if there are ways it could be made more clear I'd like to update it.

**Comment by chazlarson** [comment]
Have you read the filtering article in the wiki?

https://github.com/tellytv/telly/wiki/Running-Telly%3A-Filtering

I feel like I've covered it pretty well in there, but if there are ways it could be made more clear I'd like to update it.

There are some testing scripts linked in that article that I use to fine-tune filters.

But overall, you can filter on any field in the m3u, or on the line as a whole.  Almost every IPTV service has way too many channels, so this is something that has to be done by every user.

Almost certainly this is just a malformed filter, but it depends entirely on the setup of your provider's M3U file and the filter you're trying to use.  As a pathological example, if the "USA LOCALS" group contains 420 channels, then adding any other group would trip the "too many channels".  That seems unlikely, though.

**Comment by chazlarson** [comment]
Also, you might consider bringing this to the discord; it can be easier to discuss over there.

**Comment by s-j-daniels** [comment]
I figured it out. Unfortunately the only consistent variable for the channels I want within the m3u_plus file is tvg-id="name.us" - so I have filtered by this instead of categories.

Lots of searching and typing... but it works.
