### ISSUE TITLE
Telly don't give choice for country Hungary :(

### ISSUE THREAD

**Issue by aierwei** [tombowditch/telly#237]
**telly release with the issue:**

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):

**Description of problem:**

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**

**Comment by chazlarson** [comment]
We're going to need more details.  Telly just presents whatever choices are available from your IPTV provider.

**Comment by chazlarson** [comment]
After discussion in discord, not a telly issue.
