### ISSUE TITLE
Unclear on how to use -filterregex

### ISSUE THREAD

**Issue by sfunk1x** [tombowditch/telly#24]
I have tried using -filterregex in various forms but it seems no matter what I'm doing, it's not filtering out channels:

This doesn't seem to work:

./telly-linux-amd64 -file tv_channels_.com_plus.m3u -filterregex Arabic -filterregex French -filterregex Latino -filterregex Germany -filterregex NHL -filterregex MLB -filterregex CBN -filterregex Indian -filterregex African -filterregex Polish -filterregex Portuguese -logrequests

This also doesn't seem to work:

./telly-linux-amd64 -file tv_channels_.com_plus.m3u -filterregex Arabic French Latino Germany NHL MLB CBN Indian African Polish Portuguese -logrequests

and I've tried this:

./telly-linux-amd64 -file tv_channels_.com_plus.m3u -filterregex Arabic, French, Latino, Germany, NHL, MLB, CBN, Indian, African, Polish, Portuguese -logrequests

Any help would be appreciated.

**Comment by tombowditch** [comment]
What you're looking to do is use Regex, so none of them will work. You're mostly looking for the pipe operator - I recommend using something like regex101 to check.

Using @cesalo 's as an example - you should be able to decipher what you're looking for from this:

`-filterregex' Latino|United States|Premium Movies|Sports|United Kingdom'`

**Comment by clarenceb5** [comment]
How would this:
"-filterregex' Latino|United States|Premium Movies|Sports|United Kingdom'"
change when using Windows?

**Comment by greghesp** [comment]
I would like some more examples on how to use this if possible. Is it just searching each line by line?

As an example, my file contains:
`#EXTINF:-1 tvg-id="aande.us" tvg-name="A&E" tvg-logo="http://static.iptv-epg.com/us/AandE.us.png" group-title="US Entertainment",A&E`

What I want to do is simply filter it where group-title is "US Entertainment" and "USA Movie Networks"

I've attempted `-filterregex "US Entertainment"` although it throws back 27k channels when I know there are only 115
