### ISSUE TITLE
Set max number of streams

### ISSUE THREAD

**Issue by trentmsteel** [tombowditch/telly#25]
Is there a way to set the number of streams/tuners allowed?  At the moment Plex seems to detect Telly only capable of a single stream. But my provider supports up to 6 streams at once. Thanks

**Comment by trentmsteel** [comment]
Thanks. Also, where can I find documentation detailing this and other options for Telly, looked around and can not find it, and wiki is currently empty.

**Comment by tombowditch** [comment]
That's something we're currently working on - for now you may be able to decipher them from this: https://github.com/tombowditch/telly/blob/master/main.go#L55-L64

**Comment by trentmsteel** [comment]
Will do. Thanks again.

**Comment by HazCod** [comment]
@tombowditch aaaaand close this one aswel
