### ISSUE TITLE
Telly HD - why limit to only HD in Channel Name

### ISSUE THREAD

**Issue by DebbieFL33** [tombowditch/telly#257]
**telly release with the issue:**

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

**Description of problem:**

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**

**Comment by chazlarson** [comment]
More specifics are needed; there are no limitations on channel names.  1.1 just reads them from the M3U file, and 1.5 lets you type in whatever name you want.

**Comment by chazlarson** [comment]
Closed due to lack of any detail or a clear problem description.
