### ISSUE TITLE
Unable to add Telly with exiting HDHomeRun

### ISSUE THREAD

**Issue by After-Shock** [tombowditch/telly#26]
I have an existing HDHomeRun Prime that's hooked through Plex on Ubuntu 16.04 LTS.  With ZERO DVR's configured I input localhost:6077 and then hit continue it shows the telly tuner but then auto switches to the HDHomerun.  

With the HDHomerun configured first, I'm allowed to add Telly tuner and configure channels, match epg and finish.  Says complete and it will be downloading the program guide.  However as soon as I switch off that screen the Tuner displays: Device not found. Ensure your device is powered on and connected to your network.  

https://imgur.com/a/xhmGo
(screens to display what I'm referencing)

I'm remote currently but will try unplugging the HDHomerun tomorrow and setup telly on it's own and report back.  

edit#1
I should also report that I'm using Vaders m3u link from Xtream-editor widdled down to roughly 404 channels.

**Comment by tombowditch** [comment]
This is very interesting and something I didn't think of, also annoying to debug because I don't have a HDHomerun myself ;-)

That telly device not found error when it's all setup is normal - it has something to do with Plex pinging the device and going "oh crap we've been had" or something like that (which I am looking into and hopefully fixing soon...). 

As for trying to add when Plex finds a hdhomerun too, hmph. The problem here is that Plex knows telly exists but doesn't display it for whatever reason - I think I can guess the reason for this and I'll attempt to throw a patch soon and let you try that if that's okay?

T

**Comment by HazCod** [comment]
@After-Shock can you try building from https://github.com/HazCod/telly/tree/fix-friendlyname and report back?

I changed the FriendlyName of it to the official HDHomeRun name, just to rule that out.

**Comment by tombowditch** [comment]
If you can't build I can chuck you a binary tonight - let me know what you're running on (I assume Linux amd64?) 

T

**Comment by After-Shock** [comment]
Linux amd64, correct.  I'd appreciate the binary when possible.  I can kick the tires tonight on it at work and report back.

**Comment by tombowditch** [comment]
Sure thing - I'm home in 3 hours so I'll chuck you one then

**Comment by After-Shock** [comment]
Ready to test that binary when you have the time.

**Comment by After-Shock** [comment]
Update, was able to add the telly' tuner with the HDHomerun Disabled, I added a few test channels and matched the EPG for my area.  However I am unable to go back and add other channels due to the "Device not found" message mentioned in my original post.  Obv this isn't by design, just wanted to make sure it's something that is being addressed.

**Comment by cesalo** [comment]
I've had a similar issue (not just with telly but with others proxies). In my case (and I don't know if it will work for you) doing a quick restart of Plex fixes the issue, once Plex is restarted it finds telly again. Give it a try .. it may work for you. Sorry to not provide a root cause but testing so many things I found this workaround and so far has consistently fixed this particular issue.

**Comment by tombowditch** [comment]
Morning - my apologies @After-Shock got distracted last night. One binary coming right up...

**Comment by tombowditch** [comment]
```
[Toms-MacBook-Pro ~/code/telly] GOOS=linux GOARCH=amd64 go build
[Toms-MacBook-Pro ~/code/telly] transfer telly
######################################################################## 100.0%
https://transfer.sh/YMzVW/telly
[Toms-MacBook-Pro ~/code/telly]
```

https://transfer.sh/YMzVW/telly - let me know if this helps at all!

**Comment by moenster** [comment]
I'm facing the samme issue. Plex initially sees the "telly HDHR" but then it disappears after 10-15 seconds or so. I also have a physical HDHR, but it's the same with that one powered off. 

**From my Plex logs:** 
![image](https://user-images.githubusercontent.com/18351395/36504527-16e0c67c-1751-11e8-89e5-b6f34174d92d.png) 

**From telly command line:**
@plex:/opt/telly# ./telly-linux-amd64 -playlist=/opt/telly/iptv.m3u -listen 192.168.2.3:5004 -logrequests
[telly] [info] Reading m3u file /opt/telly/iptv.m3u...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 56 channels
[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] Building lineup
[telly] [info] listening on 192.168.2.3:5004
[telly] [request] /discover.json
[telly] [request] /lineup_status.json
[telly] [request] /discover.json
[telly] [request] /lineup_status.json
[telly] [request] /discover.json
[telly] [request] /lineup_status.json
[telly] [request] /discover.json

I tried Tom's test build above, but it didn't make i difference for me.

FWIW then I had the same issues with tvhProxy.

**Comment by tombowditch** [comment]
@moenster OK, thats progress. I've never seen the 2250 log line... huh...

I'll look into it shortly.

**Comment by moenster** [comment]
From what I can see, then telly doesn't die, but Plex seems to see it that way. I can still get the XML output from telly. 
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.2.3:5004</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
<friendlyName>telly</friendlyName>
<manufacturer>Silicondust</manufacturer>
<modelName>HDHR-2US</modelName>
<modelNumber>HDHR-2US</modelNumber>
<serialNumber/>
<UDN>uuid:12345678</UDN>
</device>
</root>

**Comment by moenster** [comment]
Ok, I updated to v. 0.4.1 and restarted PMS. The DVR appeared as connected for a short while and then returned to the "not found" state. 
/var/folders/ns/g6q6fq3s4f55hxm1w4nm83nh0000gp/T/com.apple.iChat/Messages/Transfers/Billede beskeder(900647365).png 

The strange thing is that I can actually watch the IPTV stream even though the device appears as not found.

/var/folders/ns/g6q6fq3s4f55hxm1w4nm83nh0000gp/T/com.apple.iChat/Messages/Transfers/Billede beskeder(3152616842).png

So it's absolutely a move in the right direction. Good stuff.

**Comment by porkie02** [comment]
My plex dvr says its not connected sometimes but works fine regardless.

**Comment by tombowditch** [comment]
Yeah, I think I have a problem where telly isn't telling Plex "I'm alive" properly, need to do some more debugging and probably some HTTP inspection on that front, I assume it's trying to load a URL I've missed out.

**Comment by tombowditch** [comment]
Same as @porkie02 ^^

**Comment by tombowditch** [comment]
But this seems to be especially a problem when you have an existing HDHomerun as Plex, when adding it, will just fall back to that iirc.

**Comment by porkie02** [comment]
I should dig out my homerun and have a look.

**Comment by andyblac** [comment]
just a heads up plex 'pings' the device via the SSDP protocol, you need to add a SSDP routine to your code, have a look how i managed this at my project https://github.com/OpenViX/HRTunerProxy your more than welcome to used some code, just a give me a thanks in your app.

**Comment by tombowditch** [comment]
@andyblac ooo, something I completely missed... many thanks! I'll take a look at it early next week and be sure to give you credit ;-)

**Comment by andyblac** [comment]
shoot me an email if you need help andyblac at icloud.com

**Comment by tombowditch** [comment]
Thanks mate 👍
