### ISSUE TITLE
m3u not plus

### ISSUE THREAD

**Issue by sheryus** [tombowditch/telly#260]
Hi,
i have a m3u list without plus field. How i can use it ? i have a converter or website where can convert it to m3u plus ?

**Comment by sheryus** [comment]
and if i buy a m3u in provider can look the channel on multiple tv in same time ? or 1 ip block ?

**Comment by chazlarson** [comment]
Probably the best thing for an m3u without the plus fields would be to run it through something like iptv-epg.com or xtream-editor.com.  You could come up with a script to convert, but there's a fair amount of synchronization to do which will be non-trivial.

On the multiple stream thing, it depends on how many streams your provider supports.  All the connections to your IP provider will appear to come from the Plex server machine.

BTW, this sort of question is really better suited for the Discord.
