### ISSUE TITLE
Should Telly be running ffmpeg with -re?

### ISSUE THREAD

**Issue by iMiMx** [tombowditch/telly#266]
The docs from FFmpeg state:

>     -re (input)
> 
>     Read input at native frame rate. Mainly used to simulate a grab device, or live input stream 
>     (e.g. when reading from a file). Should not be used with actual grab devices or live input 
>     streams (where it can cause packet loss).

However telly seems to start ffmpeg with -re?

`ffmpeg -re -i http://x.x.x.x:9981/stream/channelid/1916985872?profile=pass -codec copy -f mpegts pipe:1`

Would this not be classed as a 'live input stream', i.e TV? TVHeadend in this case.

**Comment by iMiMx** [comment]
Rebuilding telly 1.1 without "-re" for the ffmpeg command seems to have fixed (so far, in limited testing) my issue where streams from TVheadend -> Channels DVR via telly would stall with the below:

Jan 11 17:22:28 media telly[25195]: time="2020-01-11T17:22:28Z" level=info msg="[mpegts @ 0x55b6f36fb940] PES packet size mismatch"

Removing "-re" from the ffmpeg command, seems to cure the issue...

**Comment by iMiMx** [comment]
#267

**Comment by chazlarson** [comment]
pull request merged.
