### ISSUE TITLE
More debug information for parameter -logrequests

### ISSUE THREAD

**Issue by cesalo** [tombowditch/telly#3]
At the moment the only thing I can see is:
```[telly] [request] /lineup.json```
maybe channel requested .. IP .. etc would be beneficial in general and also if we need to troubleshoot issues.

**Comment by HazCod** [comment]
Perhaps this small modification is enough? https://github.com/HazCod/telly/commit/84855a51998b9baa50aab72da3f25b2391ed19d8

```
[telly] [warning] argument -file is deprecated, use -playlist instead !!
[telly] [info] Reading m3u file /tmp/x...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 0 channels
[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] Building lineup
[telly] [info] listening on localhost:6077
[telly] [request] 127.0.0.1:58092 -> GET /xx
```

**Comment by cesalo** [comment]
Does that show the channel requested?

**Comment by cesalo** [comment]
I just had some issues with my iptv provider and having this would've helped me a lot to determine what I missed. At the moment is similar to what I posted first:
[telly] [request] /lineup.json
[telly] [request] /lineup.json
[telly] [request] /lineup.json
[telly] [request] /lineup.json
[telly] [request] /lineup.json

I'd add channel requested, IP address, timestamp (very important) plus anything else available (maybe adding a debug flag as well?). Not sure if everything can be gathered but it would be great.

**Comment by HazCod** [comment]
See pull request https://github.com/tombowditch/telly/pull/27

@cesalo do note that Plex will fetch the channel itself, telly only supplies the download URLs to Plex.

**Comment by HazCod** [comment]
Let's close this one @tombowditch
