### ISSUE TITLE
Flawless M3U - unable to parse length

### ISSUE THREAD

**Issue by Migz93** [tombowditch/telly#33]
I read somewhere that the creator of this uses flawless hosting IPTV so i thought i'd sign up for a 48 hour trial so i could try telly out.

When i download the m3u file from flawless, save it in the same folder as telly and run

> ./telly -uktv -playlist=iptv.m3u

 I get the following: 

> [telly] [info] Reading m3u file playlist.m3u...
> [telly] [error] unable to read m3u file, error below
> [telly] [error] m3u files need to have specific formats, see the github page for more information
> [telly] [error] future versions of telly will attempt to parse this better
> panic: Unable to parse length
> 
> goroutine 1 [running]:
> main.main()
>         /Users/tom/code/telly/main.go:161 +0x199b

I've tried a free iptv playlist from the internet just to see if telly runs, picks up channels and if i can add the tuner into plex, which all works fine minus the channels not working due to i assume it being a free playlist with unreliable streams.

I also tried using the URL that flawless gave me which looks like this (obviously with my credentials):

> http://flawless-hosting.solutions:/get.php?username=xxmyemailxx&password=xxmypasswordxx&type=m3u_plus&output=mpegts

but it picks up 0 channels.

Can anyone please help? Or even tell me which IPTV the creator does use so i can follow suit.

**Comment by tombowditch** [comment]
Hey! Are you running the sed command before you're running telly?

T

**Comment by Migz93** [comment]
Hi Tom, thanks for getting back to me so quickly.

Doh! Indeed i wasn't. I'd used the sed command last night on the free IPTV playlist as i saw it was missing commas but today assumed as this utility was built around flawless that the flawless file would be ready to go. Just checked and saw no commas as explained, ran the sed command now its working fine.

So would that be why using the URL doesn't work? Instead would i have to look to make a script that will wget the m3u file, sed it and then replace the one that telly points at?

**Comment by Migz93** [comment]
Succesfully added telly with all my channels to plex, it's now going through and downloading the epg information. Tried to start streaming a couple channels and they all give me a "unable to tune channel" error message.
Is there something else i've forgot to set? I've read through all the instructions and can't see anything else that needs to be set.

**Comment by lcasey001** [comment]
Make sure it is actually working... look at the m3u file, grab the url of the channel in question and try it on VLC or something similar.

**Comment by EnorMOZ** [comment]
Make sure the channel is actually working... Look at the m3u file, grab the URL/Channel in question and try to play it on VLC or something similar.

**Comment by tombowditch** [comment]
Double check what @EnorMOZ suggested 👍

**Comment by Migz93** [comment]
Apologies, i should've mentioned i already tried this.
Clicked Plex Program Guide > Clicked Criminal Minds - Find that it's on "SKY TWO SD"
Open up my .m3u, search for " SKY TWO SD", paste TS url into VLC and it's playing fine.

I've done this with a couple different channels, literally none of my channels work in plex. Maybe my hardware isn't good enough? Running it on a shared seedbox with a poor cpu, it can handle a few transcodes at a time but maybe it cant handle live tv?

**Comment by tombowditch** [comment]
Can you curl or wget the URLs? The host or flawless may be blocking your host

**Comment by Migz93** [comment]
A wget of the url while on my seedbox downloads my .m3u file fine.

Trying to get telly setup on my local microserver to see if the issue is related to my seedbox but getting a "There was a problem adding the device" error trying to add the device. Not sure if its due to my plex being in docker. Try to solve one problem and just create more, fml.

**Comment by tombowditch** [comment]
Not the m3u, one of the .ts in the m3u please ^^

**Comment by Migz93** [comment]
Oops!

did one of the .ts, and it's giving me the below

> 
> Resolving flawless-hosting.solutions (flawless-hosting.solutions)... 94.46.195.164, 94.46.195.163
> Connecting to flawless-hosting.solutions (flawless-hosting.solutions)|94.46.195.164|:80... connected.
> HTTP request sent, awaiting response... 401 Unauthorized
> 
> Username/Password Authentication Failed.

Strange though as i'm not authenticating anything when i use it in VLC. Is this possibly the blocking you were on about?

**Comment by Migz93** [comment]
I've managed to get it running on my microserver, found that i needed to use -listen 0.0.0.0:6077 to specify to listen to more then localhost.
Getting the same issue though, again ensured that the .ts file is working.

Maybe its worth me trying another 48h trial from a different providor? Or maybe its the 48h trial itself thats causing the issue, possibly limited in some way?

**Comment by Migz93** [comment]
Grabbed a 48h trial from fabiptv and this worked straight away with the first stream i tried. So looks to either be a problem with flawless or with the 48h trial that flawless provides.

Closing issue, thanks all for the help! :)
