### ISSUE TITLE
Streams don't work on Roku or Android Phone

### ISSUE THREAD

**Issue by 12nick12** [tombowditch/telly#34]
The streams work great to watch on the web client, but for some reason they won't work on the Android or Roku client.

**Comment by tombowditch** [comment]
Is there any error provided?

**Comment by 12nick12** [comment]
Some channel just seem to fail so it starts recording if I tail -f the logs.

**Comment by tombowditch** [comment]
If only some channels are failing it's nothing to do with telly - any logs or errors would be helpful.

**Comment by 12nick12** [comment]
The channels that fail on android phone work fine on the web player.

**Comment by tombowditch** [comment]
Got any more information to help me out?

**Comment by 12nick12** [comment]
I will get you some logs tomorrow. Usually what happens is it's like it can't autoplay for in the logs it shows recording. Sorry for the delay it's been a busy day at work.

**Comment by tombowditch** [comment]
Great thanks - no worries at all ;-)

**Comment by 12nick12** [comment]
It works now. Sorry for the lack of info.
