### ISSUE TITLE
When Live TV is shared with friends and mulitple channels are watched Plex states All Tuners are Currently in use

### ISSUE THREAD

**Issue by wibuf** [tombowditch/telly#36]
I tried running telly twice on different ports but can't seem to run multiple tuners. Any workaround for this? Anybody able to watch multiple channels at the same time?
![image](https://user-images.githubusercontent.com/845898/36483235-91cfb258-16e3-11e8-8c5d-26dcddf690a8.png)

**Comment by porkie02** [comment]
I'm not sure but when Plex first launched Plex dvr me and a few friends tested with HDhomruns and we could never share Tv. It may have changed since then because I haven't tested it since. We all had HDhomeruns connected.

**Comment by tombowditch** [comment]
Instead of running telly twice have you tried using the `-streams` option? i,e, `-streams 2`

**Comment by wibuf** [comment]
Porkie, on the current version of plex, if you log into your server directly to IP. Open a friend and click restrictions, you will see the check box to Allow access to Live TV, this is pretty new.
![image](https://user-images.githubusercontent.com/845898/36484728-355361aa-16e8-11e8-9ffb-d20bdbc07bf1.png)


Thanks Tom I will look into that setting I didnt see any reference to it in the readme but I may have missed it.

**Comment by wibuf** [comment]
This resolved, should add this to the readme, thanks!
