### ISSUE TITLE
Pull m3u from URL?

### ISSUE THREAD

**Issue by dbowles1975** [tombowditch/telly#4]
Is it currently possible to pull an m3u from a URL? If not is this something that could be added? Thanks.

**Comment by tombowditch** [comment]
Definitely something that will be added very shortly!

T

**Comment by HazCod** [comment]
See https://github.com/tombowditch/telly/pull/15

**Comment by HazCod** [comment]
@tombowditch you may close this now.

**Comment by HazCod** [comment]
@tombowditch close this

**Comment by tombowditch** [comment]
@HazCod thanks
