### ISSUE TITLE
xmltv epgs

### ISSUE THREAD

**Issue by porkie02** [tombowditch/telly#42]
If you would like to use a epg other than the default Plex one you can visit. http://wiki.xmltv.org/index.php/Main_Page

Search for your country of choice and it will guide you to where you can get the relevant epg, I used the UK version and Plex mapped most of the channels correctly with only a few to map. Hopefully this helps with the tedious process of mapping.

**Comment by taylor-verys** [comment]
@porkie02 can you elaborate a little bit on this process? How does the XMLTVProject map to Tell's channel numbers?

**Comment by porkie02** [comment]
XMLTV wont maps channels, the only way to map channels using epg xml is to use your current providers epg. A lot of the time though providers epgs are not that great and the default plex one works better unless there is a good epg provider out there.

**Comment by HazCod** [comment]
I suppose this isn't specific to telly, except that perhaps we can try to return the tvg-id's if they are given in the m3u. I'm closing this one and opening a new issue for this.
