### ISSUE TITLE
telly on nVidia Shield Plex Media Server

### ISSUE THREAD

**Issue by shaneosullivanky** [tombowditch/telly#43]
There are a huge amount of people in the Plex world using nVidia Shields as their Plex Media Server. It’s basically a small powerful games console running Android TV and with hardware H264 and H265 chips which means it runs circles around most older but more powerful Intel Core i7 processors that don’t have hardware decoding.

Could telly be used on the nVidia Shield?

**Comment by porkie02** [comment]
After a short google I came across this to get docker running on a shield, I cant vouch for it or anything but it seems possible. If you got docker running on the shield then you could use the container version of telly.

http://blog.hypriot.com/post/getting-docker-running-on-a-highend-arm-gaming-console-for-fun-and-profit/

**Comment by TannerBKelly** [comment]
It appears that you can just compile it to an APK
https://github.com/golang/go/wiki/Mobile

**Comment by penfolduk** [comment]
for plex would need it to be a .bundle file so it can appear in plugins

**Comment by TannerBKelly** [comment]
If it's a separate app the couldn't it just run in the background. All it does is pass a channel list that's formatted correctly.

**Comment by Latiron** [comment]
Until nVidia opens up their code on the Shield to allow users to see and add to the plugins folder, this won't be possible. (Unless you root the Shield I guess, but no one is gonna do that as a standard).

But I agree that it could just be a standalone app like it runs in, say windows, that a user could launch before launching Plex Server.  Or if it's possible, I'm not a programmer or coder or developer, create the app so that it runs as part of a startup routine before Plex Server does.

**Comment by Latiron** [comment]
You miss my point.  A better, ideal solution, would be one where the end user, doesn't have to root their shield.  Ideally, you would want telly to function natively either running as an app on the shield or being able to drop into the plugins folder.  IMHO

**Comment by HazCod** [comment]
I'm closing this issue as this isn't specific to telly anymore.
Open this back up if any problems arise because of telly.

**Comment by shaneosullivanky** [comment]
Hi Hazcod

This isn't an issue, it is a request to be able to run telly on the nVidia shield which a huge amount of people around the world use as a plex server.

If this has to be closed and it's not possible then that's ok, but I think you might have misunderstood the original request.

**Comment by HazCod** [comment]
Hello @shaneosullivanky , APKs aren't supported officially by Go, so I deem this out of scope.
Always free to pick this up again if @tombowditch wants to.

**Comment by MentulTH** [comment]
@tombowditch is there any way we could beg you to do this?

**Comment by MentulTH** [comment]
Yes it supports it.
