### ISSUE TITLE
telly needs SSDP/UPnP

### ISSUE THREAD

**Issue by tombowditch** [tombowditch/telly#44]
According to @andyblac Plex pings the device to see if it's "alive" persay via SSDP/UPnP. telly does NOT do this currently and we'll need to implement it to allow telly to be automatically discovered and to make it properly work with existing HDHomeruns (see #26)

From @andyblac:

> just a heads up plex 'pings' the device via the SSDP protocol, you need to add a SSDP routine to your code, have a look how i managed this at my project https://github.com/OpenViX/HRTunerProxy your more than welcome to used some code, just a give me a thanks in your app.
>
> this is also how your device will be automatically seen in the plex setup screens. also make sure your UUID's are the correct length and format a simple 12345678 is not enough

T

**Comment by tombowditch** [comment]
This is also, I assume, why this currently happens sometimes:

![image](https://user-images.githubusercontent.com/5332144/36629861-69721026-1954-11e8-802d-01a2b2e62b8c.png)

**Comment by andyblac** [comment]
yup that correct, it failed the heartbeat test.

**Comment by tombowditch** [comment]
@andyblac you mention correct UUIDs and lengths - where do I find documentation for properly generating them?

T

**Comment by HazCod** [comment]
This seems about what we need: https://github.com/fromkeith/gossdp/blob/master/ssdp.go#L54

**Comment by manolodf** [comment]
Would each instance of Telly (in case you run multiple) need its own UUID and then you would be able to run 2 separate Telly Instances Simultaneously?

**Comment by tombowditch** [comment]
> Will the UUID need to stay the same for Plex is the question?

I assume so, @HazCod

**Comment by HazCod** [comment]
@tombowditch see https://github.com/tombowditch/telly/pull/48

**Comment by ElBrad** [comment]
Any update on this? I'm trying to get the EPG right for my IPTV stream but can't edit the EPG channel line up because plex says the DVR is offline. Great work on this project so far guys i've been waiting for this since Live TV & DVR was announced this will be the final piece of the jigsaw

**Comment by HazCod** [comment]
Plex saying its offline is related to the SSDP issue.

**Comment by HazCod** [comment]
Merged to main, please build a version yourself or wait for the next release.
