### ISSUE TITLE
timeout in Plex Web

### ISSUE THREAD

**Issue by Korni22** [tombowditch/telly#45]
Hey Tom!

I am trying to play basically any stream at all via Plex Web but sadly it always fails with this error message:
![imgur](https://i.imgur.com/FiVGuEv.png)

The .m3u looks like this:

```
#EXTM3U
#EXTINF:-1 tvg-id="station" tvg-name="Station" tvg-logo="xxx.xxx/picon/station.png" group-title="Germany",Station
http://xxx.xxx:8080/live/xxx/xxx/9150.ts
```

It also fails in the iOS app.

Any idea?

**Comment by porkie02** [comment]
Is it vader streams or a vader reseller? The m3u look similar. If it is vaders, they very up and down recently and I have had issues as well. It works fine with other providers.

**Comment by Korni22** [comment]
@porkie02 well, it's not vader, it might be a reseller, but I am not sure.

It works fine in VLC and MPC-HC, but won't work with telly 😢

**Comment by Korni22** [comment]
YIKES

it seems the provider seems to be whitelisting my IP - so it fails on my other machine 👀 

Let me contact them and see if they can fix it 😉 

If it's still broken after whitelisting the IP, I'll reopen the ticket!

Sorry for the annoyance!
