### ISSUE TITLE
fails to parse Freebox m3u

### ISSUE THREAD

**Issue by cpecquerie** [tombowditch/telly#46]
Hi !
Great tool, couldn't wait to test it ;-)

I get the following error with Freebox m3u (French Internet provider with free IPTV stream)
```
goroutine 1 [running]:
main.main()
        /go/src/app/main.go:180 +0x1b9f
[telly] [info] booting telly v0.4.3
[telly] [info] Reading m3u file "/config/playlist.m3u"...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

Extract of the m3u:
#EXTM3U
#EXTINF:0,2 - France 2 (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=sd
#EXTINF:0,2 - France 2 (bas débit)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=ld
#EXTINF:0,2 - France 2 (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=hd
#EXTINF:0,2 - France 2 (auto)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201
#EXTINF:0,3 - France 3 (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=hd
#EXTINF:0,3 - France 3 (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=sd
#EXTINF:0,3 - France 3 (bas débit)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202&flavour=ld
#EXTINF:0,3 - France 3 (auto)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=202
#EXTINF:0,5 - France 5 (auto)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=203
#EXTINF:0,5 - France 5 (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=203&flavour=hd
#EXTINF:0,5 - France 5 (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=203&flavour=sd
#EXTINF:0,7 - Arte (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=204&flavour=sd
#EXTINF:0,7 - Arte (bas débit)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=204&flavour=ld
#EXTINF:0,7 - Arte (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=204&flavour=hd
#EXTINF:0,7 - Arte (auto)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=204
#EXTINF:0,8 - C8 (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=372&flavour=sd
#EXTINF:0,10 - TMC (bas débit)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=497&flavour=ld
#EXTINF:0,10 - TMC (HD)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=497&flavour=hd
#EXTINF:0,10 - TMC (standard)
rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=497&flavour=sd
#EXTINF:0,10 - TMC (auto)
```

Thanks,
Christophe.

**Comment by tombowditch** [comment]
As seen in [these lines of the parser](https://github.com/tombowditch/telly-m3u-parser/blob/master/m3u.go#L25-L27), this means telly was unable to open the m3u. Does it have permission for it? By chance, are you using Docker?

T

**Comment by cpecquerie** [comment]
Yes I am using docker, the m3u has read permissions for everyone.
Any idea?
Thanks

**Comment by EnorMOZ** [comment]
@cpecquerie , Please provide as much detail on how you are running this in docker. Command, volumes/mounts etc.

**Comment by cpecquerie** [comment]
Sure, I am running telly though docker-compose, here's the config I have 

   telly:
     container_name: telly
     image: tombowditch/telly
     ports:
       - "8071:6077"
     environment:
       - PLAYLIST="/config/playlist.m3u"
     volumes:
       - /sharedfolders/docker/telly:/config
     restart: unless-stopped

**Comment by EnorMOZ** [comment]
@cpecquerie that "looks" correct. Can you confirm that volume is actually mounted by running a `docker inspect -f '{{ .Mounts }}' containerid`. Also can you try using the "url" to the m3u vs file to see if that works ?

**Comment by HazCod** [comment]
Can you also confirm that /sharedfolders/docker/telly/playlist.m3u is readable by the user docker runs as? Try a `docker exec -ti <name-of-container> ls -al /config/`

**Comment by EnorMOZ** [comment]
@HazCod that is not going to work as the base is a "scratch" container which does not contain "ls" "bash" etc. He will have to get the $PID of that running container with something like `docker inspect -f '{{.State.Pid}}' telly` then as root `ls -lrt /proc/$PID/root/` and `ls -lrt /proc/$PID/root/config/` That should give us a good listing of file permissions.

**Comment by cpecquerie** [comment]
@HazCod I got `[{bind  /sharedfolders/docker/telly /config  rw true rprivate}]` from this command
` docker inspect -f '{{ .Mounts }}' telly`
@EnorMOZ your command `docker inspect -f '{{.State.Pid}}' telly` returns 0  which does not seem right.

When I try with the URL, it also fails to open the m3u, here's the log
```
[telly] [info] booting telly v0.4.4
[telly] [info] Reading m3u file "http://mafreebox.freebox.fr/freeboxtv/playlist.m3u"...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file
```

**Comment by cpecquerie** [comment]
Just a quick update, I tried to run the binary directly and it works with this command :  `./telly -playlist http://mafreebox.freebox.fr/freeboxtv/playlist.m3u` so it's definitely related to docker.

**Comment by lcasey001** [comment]
@cpecquerie Can you run this `docker inspect -f '{{.State}}' telly`.  When you ran the binary directly was it from the same box as the container ?
Also feel free to join the discord channel you would probably get more help there and in real time.

**Comment by HazCod** [comment]
I tried testing the playlist myself, but the site isn't reachable?

    curl -v http://mafreebox.freebox.fr/freeboxtv/playlist.m3u
    *   Trying 212.27.38.253...
    * TCP_NODELAY set
    -timeout-

**Comment by HazCod** [comment]
Closing since inactive..
