### ISSUE TITLE
-streams not working

### ISSUE THREAD

**Issue by 12nick12** [tombowditch/telly#47]
Does it matter what location we put the -streams 4? It doesn't seem to be working. Plex is only allowing one stream at a time. Also even when telly is running Plex shows that the tuner is offline, but it's still functional.

**Comment by tombowditch** [comment]
First part of your issue: restart Plex when setting -streams

Second part: see #44, it's something we're working on

**Comment by 12nick12** [comment]
OK. Awesome. You rock. Where can I shoot donations?
