### ISSUE TITLE
Possible docker image change required for Kitematic

### ISSUE THREAD

**Issue by picto3000** [tombowditch/telly#49]
I've got the docker running in Kitematic, but can't get it to create the temp m3u file.
`[telly] [info] booting telly v0.4.3`
`[telly] [error] Could not create file: /tmp/telly.m3u ; open /tmp/telly.m3u: no such file or directory`

It's possible when creating the image the VOLUME argument needs to be defined, but I am a newbie to dockers.

**Comment by EnorMOZ** [comment]
You will need to mount /tmp when you run the container for now. I pinged @tombowditch on discord about a possible permanent solution.

**Comment by picto3000** [comment]
I don't believe Kitematic allows the arbitrary mounting of volumes.
If I could use a command line argument to set a tmp location, I may be able to get around this.

**Comment by tombowditch** [comment]
@picto3000 as of #52 the `-temp` argument is now possible + Docker (if you pull again) defaults to /

**Comment by HazCod** [comment]
We fixed this in the latest commit, I suppose this can be closed @tombowditch ?

**Comment by tombowditch** [comment]
Sounds good, let me know if you need anymore help @picto3000

**Comment by picto3000** [comment]
Kitematic is now working. Thanks!

 

-Shaun

0413 911 938
