### ISSUE TITLE
Can't setup DVR

### ISSUE THREAD

**Issue by gignonje** [tombowditch/telly#5]
First of all, thank you for this promising software.

I tried to setup Telly but I can't manage to get past the DVR setup. It tries to get the channel list but then shows an error.

My Plex Media Server version is 1.11.1.4760.

![capture d ecran 2018-02-08 a 18 52 23](https://user-images.githubusercontent.com/1492645/35989387-5416050c-0d01-11e8-9a7f-6678f2ab6fa1.png)

This is what I get from the terminal
```
# ./telly -file playlist.m3u
[telly] [parser] Reading m3u file playlist.m3u ...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -useregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 131 channels

[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] listening on localhost:6077
2018/02/08 18:53:45 http: panic serving 127.0.0.1:43795: runtime error: index out of range
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc420093040)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1697 +0xd0
panic(0x684ea0, 0x849410)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
main.main.func6(0x81ff40, 0xc42013c000, 0xc420138000)
	/Users/tom/go/src/github.com/tombowditch/telly/main.go:204 +0x4a9
net/http.HandlerFunc.ServeHTTP(0xc42008cd80, 0x81ff40, 0xc42013c000, 0xc420138000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0x853b60, 0x81ff40, 0xc42013c000, 0xc420138000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4200a2c30, 0x81ff40, 0xc42013c000, 0xc420138000)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420093040, 0x820480, 0xc4200a8440)
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.9/libexec/src/net/http/server.go:2720 +0x288
```

Do you know what I've done wrong ? I've tried to pass m3u file with only one (working) channel, but that doesn't fix it.

Thank you

**Comment by Nezreka** [comment]
Do you mind sharing your m3u file? I'm unable to get it to read my own

**Comment by tombowditch** [comment]
@gignonje what version of telly are you running? This should be fixed in [v0.2](https://github.com/tombowditch/telly/releases/tag/v0.2) - if you're using that version, let me know and I'll take a look.

---------------------

@Nezreka what issue are you having? Please open a new one if it's not the same error ;-)

T

**Comment by dpohlman** [comment]
I am seeing something very similar, running v0.2 tried both in Windows and Linux and it looks like everything is running with the script shows 188 channels available litening on port 6077, but Plex never finds it when I try to add manually.  Ran nmap on both windows and linux and I don't show port 6077 as open.

**Comment by gignonje** [comment]
@tombowditch I was in v0.1 and v0.2 fixed it, thanks !

@Nezreka I had an issue about `Invalid m3u file format. Expected #EXTM3U file header`, if this the issue you have, I just had to convert from UTF-8 encoding to ISO-8859-1 to get it to work. I don't know why.
