### ISSUE TITLE
Virus in telly-windows-386.exe ?

### ISSUE THREAD

**Issue by BenPicard** [tombowditch/telly#51]
I can't download telly-windows-386.exe. Windows is removing the file every time and it's telling me that there is a virus.

Ben

**Comment by tombowditch** [comment]
Browsers flag .exe's by default. telly does not ship with any viruses - you can build it yourself using `go build` or if you're not on Windows, `GOOS=windows GOARCH=amd64 go build`

**Comment by tombowditch** [comment]
Closing this due to lack of response, let me know if I can be of further help (just reopen the issue!).
