### ISSUE TITLE
MAC addresses and telly

### ISSUE THREAD

**Issue by smoothrunnings** [tombowditch/telly#55]
I am missing in the how-to set this up. All IPTV services require you to provide them with a MAC address to connect to their servers. I don't see any of that in the how-to. So how does this work? You have to explain it like we are all 3 year old's if you want it to be super popular! :)

**Comment by tombowditch** [comment]
> All IPTV services require you to provide them with a MAC address to connect to their servers.

A MAC address is an optional field when signing up for IPTV providers. telly takes your m3u file and transforms it so that Plex can deal with it.

**Comment by smoothrunnings** [comment]
Wrong. A MAC address is REQUIRED by your IPTV service provider this is how they allow you access to their server. I have used IPTVExpress, Voodoo, Crown, and many others. They don't just let you connect freely, it requires a Mag compatible box and they MAC address.

**Comment by HazCod** [comment]
This is a bit unrelated to telly. I suppose you can use the MAC address of the interface of the server you're running telly on?

**Comment by tombowditch** [comment]
@smoothrunnings - it maybe be required on your provider, but any provider I've ever used doesn't require it. You can just provide the MAC address of the interface of the server you're running telly on, I suppose, like @HazCod suggested.

**Comment by smoothrunnings** [comment]
You can't do that. IPTV MAC addresses all start with 00:1A:78:xx:xx:xx you can't get that from a regular NIC. I am surprised you haven't experienced this.. It's nothing new, I have been watching different IPTV services providers for the last 4 years. It started with IPGuys.

**Comment by HazCod** [comment]
Then you'll need to change the MAC of your interface to start with 00:1A:78 or there's nothing we can do for you.

**Comment by smoothrunnings** [comment]
You could start by writing a problem that meets industry standards!

**Comment by tombowditch** [comment]
@smoothrunnings - help us understand. What are MAC addresses in IPTV used for? To my understanding, they're used for something like a MAG box. I think you're misunderstanding what telly is and what it's used for.

**Comment by Dec64** [comment]
that's for Mag IPTV, not all iptv services are MAG protocol. Use a different provider or ask your providor to give you a m3u playlist.

**Comment by tombowditch** [comment]
Thanks @Dec64 👍

**Comment by shaneosullivanky** [comment]
My IPTV provider doesn’t require a MAC address, I can use the M3U file on any device I want as long as it’s not at the same time. Some IPTV providers may look for a MAC address to lock the m3u file to that device only, that is provider specific and not the case for all providers.

**Comment by manolodf** [comment]
Most IPTV Providers do not require a Mac address contrary to what smoothrunnings says, only the ones that provide the Stalker/MAG service is MAC address based, the normal ones, and the ones Telly is designed for and will work for plex are the ones that are M38 Playlist based, totally different types of service.   The Stalker/Mag ones are more designed like a Set-Top Box or to use something like Smart-STB, the m3u playlist ones are the majority and give you the flexibility  of using telly.   Just a few names that come up are Vaders, Flawless, Limitless, Gears, and various others are m3u based, some do have an IP lock, but not all.

**Comment by HazCod** [comment]
Let's just close this @tombowditch. OP is uncivil and we made our point.
