### ISSUE TITLE
Australian IPTV - m3u(8) woes

### ISSUE THREAD

**Issue by spankhur** [tombowditch/telly#56]
Hi,
New to IPTV and playlist files so please excuse any basic ignorance that shows through :)

I have your Telly docker installed on unraid and have found a source of Australian IPTV from here:
     https://www.matthuisman.nz/2017/07/australia-iptv-epg-files.html

From the instructions on that page I determined the relevant URL as:
      TV: http://iptv.matthuisman.nz/au/Adelaide/raw-tv.m3u8

and plugged that into the docker config (Path or URL to m3u playlist from IPTV Provider:)

Result I'm getting is that the docker fails to start and the log shows:
[telly] [info] booting telly v0.4.4
[telly] [info] Downloading file http://iptv.matthuisman.nz/au/Adelaide/raw-tv.m3u8 to /telly.m3u
[telly] [error] Could not download: Get https://raw.githubusercontent.com/matthuisman/iptv/9d837a45e637b4c6f59b9ffd8faa7a09f10eaf90/au/Adelaide/raw-tv.m3u8: x509: failed to load system roots and no roots provided

Not sure if I'm missing something obvious, or what I'm trying to do is simply not supported - would very much appreciate any guidance.

** not sure if it helps, but this same URL works using the IPTV plugin within Plex **

Thanks,
Shane.

**Comment by tombowditch** [comment]
Okay, this is nothing to do with you ;-) and a telly issue. It's something to do with the CA certificates - kind of related to this: https://github.com/zenazn/goji/issues/126#issuecomment-100063848

Will find a fix today and get back to you!

**Comment by HazCod** [comment]
This is because go expects CA root certificates to be present on the filesystem, but as we're using a scratch (empty) filesystem it lacks these. Package in question is `ca-certificates` on alpine.

I will create a PR.

**Comment by tombowditch** [comment]
Looks good, I'll get this merged!

**Comment by tombowditch** [comment]
@spankhur can you try pulling again and letting us know if this fixes it for you?

**Comment by HazCod** [comment]
Closing this since no response. Comment if you still see any issues.

**Comment by spankhur** [comment]
Hi Tom,
sorry for the delay, I've been travelling wtih no access to my server.
Pulled new version down and immediate success :)

I''ve just started the Plex DVR setup process (downloading EPG info now) and have my fingers crossed.

Thanks for your help.

**Comment by tombowditch** [comment]
Not a problem @spankhur - sounds good! ;-)
