### ISSUE TITLE
Unable to tune channel error

### ISSUE THREAD

**Issue by Hengjie** [tombowditch/telly#59]
I'm running Telly command below and though it's added successfully, it errors out when playing

```
./telly-linux-amd64 -playlist="https://raw.githubusercontent.com/matthuisman/iptv/master/nz/tvh-tv.m3u8" -streams=1
[telly] [info] booting telly v0.4.5
[telly] [info] Downloading file https://raw.githubusercontent.com/matthuisman/iptv/master/nz/tvh-tv.m3u8 to /tmp/telly.m3u
[telly] [info] Reading m3u file /tmp/telly.m3u...
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 15 channels
[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] Building lineup
[telly] [info] listening on localhost:6077
```

I get a `Unable to tune channel (Timed out)` error. 

There are no errors in telly stdout. I'm running this on Ubuntu 17.04 with plex media server v1.12.0.4829.

**Comment by HazCod** [comment]
Have you tried restarting plex? If nothing shows up in telly, it means plex does not try to connect to it.

**Comment by tombowditch** [comment]
@Hengjie an error like that is nothing to do with telly - It'd more be your IPTV provider having issues or blocking you. Try opening up the m3u, finding the `.ts` url and `wget`-ing that and see if it works or errors.

T

**Comment by Hengjie** [comment]
Wow! Thanks for the quick responses! With Telly, I tried accessing the URLs and they appear to be working. Though when I wget the first `tv.9.m3u8` file I only get a 4979 byte file. Could that be the problem?

`lineup.json` output:
```
[{"GuideNumber":"10000","GuideName":"001","URL":"http://iptv.matthuisman.nz/nz/tv.9.m3u8"},{"GuideNumber":"10001","GuideName":"002","URL":"http://iptv.matthuisman.nz/nz/tv.10.m3u8"},{"GuideNumber":"10002","GuideName":"003","URL":"http://iptv.matthuisman.nz/nz/tv.11.m3u8"},{"GuideNumber":"10003","GuideName":"004","URL":"http://iptv.matthuisman.nz/nz/tv.12.m3u8"},{"GuideNumber":"10004","GuideName":"005","URL":"http://iptv.matthuisman.nz/nz/tv.51.m3u8"},{"GuideNumber":"10005","GuideName":"006","URL":"http://iptv.matthuisman.nz/nz/tv.55.m3u8"},{"GuideNumber":"10006","GuideName":"007","URL":"http://iptv.matthuisman.nz/nz/tv.46.m3u8"},{"GuideNumber":"10007","GuideName":"008","URL":"http://iptv.matthuisman.nz/nz/tv.45.m3u8"},{"GuideNumber":"10008","GuideName":"009","URL":"http://iptv.matthuisman.nz/nz/tv.7.m3u8"},{"GuideNumber":"10009","GuideName":"010","URL":"rtmp://streamer1.streamhost.org/salive/GMIFLNL"},{"GuideNumber":"10010","GuideName":"011","URL":"http://iptv.matthuisman.nz/nz/tv.21.m3u8"},{"GuideNumber":"10011","GuideName":"012","URL":"http://iptv.matthuisman.nz/nz/tv.18.m3u8"},{"GuideNumber":"10012","GuideName":"013","URL":"http://iptv.matthuisman.nz/nz/tv.60.m3u8"},{"GuideNumber":"10013","GuideName":"014","URL":"http://iptv.matthuisman.nz/nz/tv.redbull.tv.m3u8"},{"GuideNumber":"10014","GuideName":"015","URL":"http://iptv.matthuisman.nz/nz/tv.sbnint.m3u8"},{"GuideNumber":"10015","GuideName":"001","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101305020522.m3u8"},{"GuideNumber":"10016","GuideName":"002","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101305020525.m3u8"},{"GuideNumber":"10017","GuideName":"003","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101305020523.m3u8"},{"GuideNumber":"10018","GuideName":"004","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101204200427.m3u8"},{"GuideNumber":"10019","GuideName":"005","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101204200428.m3u8"},{"GuideNumber":"10020","GuideName":"006","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101204200424.m3u8"},{"GuideNumber":"10021","GuideName":"007","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101002210221.m3u8"},{"GuideNumber":"10022","GuideName":"008","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101002210222.m3u8"},{"GuideNumber":"10023","GuideName":"009","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101002210224.m3u8"},{"GuideNumber":"10024","GuideName":"010","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101002210220.m3u8"},{"GuideNumber":"10025","GuideName":"011","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101204200421.m3u8"},{"GuideNumber":"10026","GuideName":"012","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.320203000304.m3u8"},{"GuideNumber":"10027","GuideName":"013","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.fox.sports.news.m3u8"},{"GuideNumber":"10028","GuideName":"014","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.320203000305.m3u8"},{"GuideNumber":"10029","GuideName":"015","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101305020528.m3u8"},{"GuideNumber":"10030","GuideName":"017","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.320203000301.m3u8"},{"GuideNumber":"10031","GuideName":"018","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.320203000302.m3u8"},{"GuideNumber":"10032","GuideName":"019","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101305020520.m3u8"},{"GuideNumber":"10033","GuideName":"020","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc1.m3u8"},{"GuideNumber":"10034","GuideName":"021","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc2.m3u8"},{"GuideNumber":"10035","GuideName":"022","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc3.m3u8"},{"GuideNumber":"10036","GuideName":"023","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc4.m3u8"},{"GuideNumber":"10037","GuideName":"024","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc5.m3u8"},{"GuideNumber":"10038","GuideName":"025","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc6.m3u8"},{"GuideNumber":"10039","GuideName":"026","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc7.m3u8"},{"GuideNumber":"10040","GuideName":"027","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.7misc8.m3u8"},{"GuideNumber":"10041","GuideName":"029","URL":"http://iptv.matthuisman.nz/au/Sydney/tv.101406020625.m3u8"}]
```

**Comment by mattstutter** [comment]
I ran into the same problem with the iptv.matthuisman.nz m3u8 link.  I've tried with the RAW version as well.  

I presume it's as Tom is saying the link isn't a .TS feed, but points off to another m3u8 link that takes care of it.

**Comment by HazCod** [comment]
I think I had the same thing in muxy, with the channel m3u containing rotating TS files.

**Comment by haxcop** [comment]
Hey guys, i just ran into a similar issue, in my case is that i was able to tune the channels and everything perfect for hours but later i got nothing available on my program guide
see the attachments pics
btw using vaders and the program guide epg from Plex(gracenote Sky HD)

![screen shot 2018-03-07 at 07 37 46](https://user-images.githubusercontent.com/7826906/37079655-38d63002-21db-11e8-98de-d4c8999fc62e.png)
![screen shot 2018-03-07 at 07 37 29](https://user-images.githubusercontent.com/7826906/37079657-3b052734-21db-11e8-9a94-0cd92e70952a.png)

**Comment by kalyway** [comment]
I'm getting the same issues with a premium IPTV m3u playlist. It works for my friend no problems. Not using telly though.

**Comment by slamanna212** [comment]
I have the same issue as @haxcop using Vaders. I hastily set it up last night running the linux executable. I am redoing it right now inside of docker so il see if that changes anything

**Comment by kalyway** [comment]
So, this is what helped me. Using a reseller of Vaders (PM Club) list. I setup using linux executable on Ubuntu. I was also running Plex in a docker. What I did was setup telly and THEN restarted Plex THEN setup using Live DVR in Plex. Worked just fine.

**Comment by slamanna212** [comment]
@kalyway and has it lasted for more than a couple hours? 

Also, when you go to browse channels, does it show you EVERY single channel, or only the channels you have mapped

**Comment by taylorbourne** [comment]
I'm a Vaders user as well and have seen this happen when pasting the m3u directly as it was listed on my providers website:
`http://vaders.tv:80/get.php?username=USERNAME&password=PASS&type=m3u_plus&output=m3u8`
Simply changing the `output` parameter worked for me:
`http://vaders.tv:80/get.php?username=USERNAME&password=PASS&type=m3u_plus&output=ts`
👍

**Comment by HazCod** [comment]
Thanks @taylorbourne , we will specify this in the README.

**Comment by mattstutter** [comment]
Any suggestions on how to get a ts version? The original poster and myself are not using Vader’s list. We’re using the link above.

**Comment by HazCod** [comment]
Try asking in the forums of your provider

**Comment by kalyway** [comment]
As someone who has vader streams I can definitely say that taylorbourne's suggestion is not working for me.

**Comment by slamanna212** [comment]
Using taylorbournes suggestion and using Vader's. Mine is working great!

**Comment by kalyway** [comment]
Oh, I'll try it again then. My apologies! 😃

**Comment by haxcop** [comment]
@taylorbourne HI good point on that - so in escense we have two known methods to grab the m3u8 list from vaders 
besides the two ones you provide there's a another one that download the links into the m3u8 with a token instead of .ts / .mp4 / .mkv
`http://api.vaders.tv/vget?username=username&password=password&format=ts` 
and this can also be asked as `=m3u8`

I have had this funny thing recently with unable to tune the channel on vaders. so it maight be related?. i'll performing a sanity check and let you know the output
