### ISSUE TITLE
Acquired a m3u file and used sed -i to change to proper format but still unable to run the file.

### ISSUE THREAD

**Issue by Nezreka** [tombowditch/telly#6]
this file in particular.

https://raw.githubusercontent.com/fluxustv/IPTV/master/list.m3u

**Comment by cesalo** [comment]
Did you run the sed from the readme section to add the comma after the -1?

**Comment by Nezreka** [comment]
Yeah i sure did. I 'll send a copy of my file now.

**Comment by tombowditch** [comment]
From your file, here's an example line:

```
#EXTINF:-1 tvg-logo="http://i.imgur.com/CvQCnwZ.png" group-title="INFO",* Fluxus IPTV
https://archive.org/download/fluxustv/Fluxus_TV.mp4
```

It _should_ be:

```
#EXTINF:-1, tvg-logo="http://i.imgur.com/CvQCnwZ.png" group-title="INFO",* Fluxus IPTV
https://archive.org/download/fluxustv/Fluxus_TV.mp4
```

Notice the comma after `#EXTINF:-1`

T

**Comment by skiman6010** [comment]
Even after changing that by running `sed -i 's/#EXTINF:-1/#EXTINF:-1,/g' myiptv.m3u` it still doens't work.

**Comment by tombowditch** [comment]
Enhancement: telly should automatically do this in the future

**Comment by tombowditch** [comment]
@skiman6010 what error you getting? If unrelated please open a new issue 👍

**Comment by skiman6010** [comment]
```
[telly] [warning] using default m3u option, 'iptv.m3u'. launch telly with the -file=yourfile.m3u option to change this!
[telly] [parser] Reading m3u file iptv.m3u ...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to parse length

goroutine 1 [running]:
main.main()
        /Users/tom/code/telly/main.go:80 +0x1a15
```

**Comment by tombowditch** [comment]
@skiman6010 can you post a couple lines of your m3u, censored?

**Comment by skiman6010** [comment]
```
#EXTINF:-1, tvg-logo="http://i.imgur.com/CvQCnwZ.png" group-title="INFO",* Fluxus IPTV
<url>

#EXTINF:-1, tvg-logo="http://i.imgur.com/pYWMEWN.png" group-title="INFO",+ Free IPTV
<url>```

How's that? Not sure what you all wanted censored.

**Comment by brian21158** [comment]
Hey, I'm having the same issue, here's my first few lines as well:

#EXTM3U
#ENTINF:-1, tvg-name="TFC" tvg-id="None" tvg-logo="" group-title="Filipino",TFC
http://*****

**Comment by tombowditch** [comment]
@skiman6010 you able to send me your m3u (or parts of it) in private so I can debug locally?

---------

@brian21158 see above ^

------------

My email's on my Github page


T

**Comment by tombowditch** [comment]
@Nezreka @skiman6010 

There's two streams in your m3u file that have a length of 0, and the `sed` didn't catch:

```
cat iptv.m3u|grep "EXTINF:0"
#EXTINF:0 tvg-logo="http://lared.cl/app/themes/lared-theme/img/icons/apple-touch-icon.png" group-title="CHILE",La Red
#EXTINF:0 tvg-logo="http://i.imgur.com/xBgH1Tw.jpg" group-title="CHILE",Maxima TV
```

Try performing another sed like this:

```
sed -i 's/#EXTINF:0/#EXTINF:0,/g' myiptv.m3u
```

Let me know if that helps.

T

**Comment by skiman6010** [comment]
@tombowditch Whoops! Rookie mistake. I didn't even think about sed missing lines like that. I'm pretty new to m3u files. Thanks for your help. :)

**Comment by tombowditch** [comment]
@skiman6010 no worries, you pointed out a thing I need to add to the README though, so thanks 👍 

T

**Comment by Nezreka** [comment]
@tombowditch That fixed it, thank you!

**Comment by Nezreka** [comment]
@tombowditch I have a new issue now. Everything loads properly onto plex with the guide but no matter what I choose it loads for 20 seconds and gives a tuner error. Any suggestions?

**Comment by tombowditch** [comment]
@Nezreka can you enable Plex Media Server debug log and check the log file when you start a stream?

**Comment by tombowditch** [comment]
telly no longer requires this sed command.

----------------

@Nezreka closing this for now as no reply, reopen if you're replying ;)
