### ISSUE TITLE
Recordings stop after a couple of minutes

### ISSUE THREAD

**Issue by jamesdisco** [tombowditch/telly#62]
My recordings are stopping from anywhere between 30 seconds and 15 minutes, telly doesn't seem to show any errors and neither does plex. I've attached my logs.
[Plex Media Server Logs_2018-03-05_11-33-10.zip](https://github.com/tombowditch/telly/files/1780741/Plex.Media.Server.Logs_2018-03-05_11-33-10.zip)
Watching live works well and my other DVB-T tuners record the full programme.
I'm using the following line in my batch file to start telly in windows 10:
start /d "C:\Users\Mayserver\Desktop" telly.exe -uktv -streams 3
Anyone else having the same problem.

**Comment by HazCod** [comment]
Does the telly log tell anything? Because this looks like it's Plex related.

**Comment by tombowditch** [comment]
Been using telly for a couple weeks now and it seems to record most recordings. I wonder if it's related to #44 maybe @andyblac can confirm?

@jamesdisco Plex forum thread + reddit posts are planned once v0.5 is out 👍 
T

**Comment by jamesdisco** [comment]
All seems well now, recordings are fully completing. Looking forward to getting chanel nos. working will make matching so much easier. Thanks again.
