### ISSUE TITLE
Advanced Filtering

### ISSUE THREAD

**Issue by lellimecnar** [tombowditch/telly#65]
Rather than just matching channels that _contain_ a specified string, I'd like to be able to _exclude_ channels that contain a string, or start/end with a string.

(I tried using negative lookarounds, but go doesn't support them)

**Comment by lellimecnar** [comment]
If there's an `exclude` option added, it would make sense to implement #64 for it as well.

**Comment by robbiet480** [comment]
Implemented in v1.0.0!
