### ISSUE TITLE
What would you like to see in telly?

### ISSUE THREAD

**Issue by tombowditch** [tombowditch/telly#7]
Hello all folks from reddit,

**What would you like to see in telly?**

T

**Comment by Capricom** [comment]
A docker image would be pretty awesome. I'm new to docker but from what I've seen it should be relatively easy to do.

**Comment by After-Shock** [comment]
+1 for Docker image as well.

**Comment by ninthwalker** [comment]
This would be super simple as a docker since he's already made it an executable. Just spin up a quick ubuntu baseimage or your linux of choice and map a volume/port and good to go.

**Comment by wdaly** [comment]
Can you run more than one .m3u? if not that would be cool.

**Comment by HazCod** [comment]
For Docker support, see my PR https://github.com/tombowditch/telly/pull/11

**Comment by tombowditch** [comment]
@Capricom @After-Shock @ninthwalker can you check out @HazCod PR #11 and let me know what you think? I've little experience with Docker so your input would be appreciated!

T

**Comment by DJCallyman** [comment]
Mac OS release?

**Comment by tombowditch** [comment]
@DJCallyman macOS release exists. Check https://github.com/tombowditch/telly/issues/9

**Comment by TannerBKelly** [comment]
the iptv m3u that I pull from also has a epg that come with it. Can I load that in here some how?

**Comment by Dec64** [comment]
@TannerBKelly You can use it via plex not via telly.

@tombowditch Some way to poll the stream url's within the m3u to check if they are up or not, and replace them on the fly in the m3u with backup links.

**Comment by tombowditch** [comment]
@Dec64 seems interesting, can you open a new issue about this? We'll discuss it there.

**Comment by cesalo** [comment]
headless option to run it like a daemon? I mean it can be done with a simple nohup using your binary .. but i think it would be nice to have it anyway.

**Comment by tombowditch** [comment]
Just thought I'd let you know @Capricom @After-Shock @ninthwalker telly is now available @ https://hub.docker.com/r/tombowditch/telly/ 👍

**Comment by shaneosullivanky** [comment]
Great work, just got it working on windows. Is there a version for the nVidia Shieled planned?

**Comment by tombowditch** [comment]
@shaneosullivanky can you give more information on the nvidia shield? What does it run? I assume Android? What would telly have to be? An Android app?

T

**Comment by shaneosullivanky** [comment]
Ya it could be tricky. 

Runs Android TV so I’d say it might have to be an app. Currently a lot of us running IPTV on an enigma2 Box (satellite tuner) in uk and ireland. That has a plug-in called HrTunerProxy which makes it show up as a tuner in Plex. There’s a guy on the Plex forums AndyBlac who made it and he seems to know a lot about it. Not sure if it’s worth asking him? I’ll mention telly on that forum as it blows what we’re currently using out of the water. Lot of guys in work have nVidia Shields as PMS so would be great if it worked for them as well.

Great work!!

**Comment by tombowditch** [comment]
Yeah it's something that'd be worth looking into. Open a new issue on Github and we'll start looking into it ;-)

**Comment by picto3000** [comment]
The ability to set the tmp location via an argument would be great.
I've got the docker running in Kitematic, but can't get it to create the temp m3u file.
`[telly] [info] booting telly v0.4.3`
`[telly] [error] Could not create file: /tmp/telly.m3u ; open /tmp/telly.m3u: no such file or directory`

**Comment by tombowditch** [comment]
@picto3000 definitely something to look into - open an issue on it for me ;-)


-----


@EnorMOZ will be able to give more insight (I believe), but you'll have to mount (or attach?) /tmp, sorry for being vague - I'm not much of a Docker guy :-)

**Comment by picto3000** [comment]
Will do. I've only started using Docker today with telly. So I'm not that experienced and could be missing something.

**Comment by EnorMOZ** [comment]
@picto3000 check #50

**Comment by dqans** [comment]
Support for Channels app on AppleTV. I _believe_ this will only work over UDP, hence Telly does not currently work. Long shot but figured I'd ask.

**Comment by 12nick12** [comment]
@cesalo Depending on your Linux version you can do SystemD. Here the systemd file I created https://pastebin.com/n9HJ0ymC. Then after you do that run "systemctl daemon-reload" then "systemctl start telly" then "systemctl enable telly" this will enable it on boot.

**Comment by cesalo** [comment]
@12nick12 Thanks. I guess at the end you can gain the same using the docker image.

**Comment by 12nick12** [comment]
@cesalo I guess so. I personally don't have much knowledge with with Docker so I try to stay away from it lol.

**Comment by maekillam** [comment]
Any chance this could be made into a QPKG ? I would like to run it on my Qnap but don’t have enough ram for virtualization. This seems a much more elegant solution compared to TVHeadend and tvh proxy.

**Comment by diswell** [comment]
Runs fine on Qnap devices, without the need for a QPKG. Copy it to the NAS, run it from an SSH prompt.

**Comment by ioan-rosca** [comment]
How can i use this in synology? any chance to get an *.spk? docker container not working.

**Comment by KunfuMunky** [comment]
It would indeed be nice to have it as and QPKG. I already tried what @maekillam said but after Googling for an hour I still didn't find oud how to run it properly haha! I know I'm still a newbie in these things but with an QPKG it would be a lot easier haha! Thanks!

**Comment by maekillam** [comment]
I’m still looking for how to do this as well @KunFuMunky. I figured out how to ssh onto the QNAP but I can’t figure out which release version to use.

**Comment by KunfuMunky** [comment]
Yeah I have the same issue like that to... Doesn't @diswell know how this works? He sounds like the only guy who has this working right?

**Comment by diswell** [comment]
The version depends on the processor you have in your QNAP.. You want the Linux release, but select the amd64 if it's a faster Intel CPU or the respective ARM if you have an old ARM CPU. Most modern QNAP NAS devices are running on Intel CPUs nowadays so that what I'd go with first, but check your spec sheets.

**Comment by KunfuMunky** [comment]
Hey @diswell, I have TS-453B but what I don't understand is how you install a Linux file on a different operating system. You probably find this a stupid question but yeah :P .

**Comment by diswell** [comment]
QNAP runs a Linux variant as its underlying OS. All you need to do is copy the telly file to your NAS using your regular PC. Then log in via SSH, navigate to the folder to which you copied the file and run from there. Obviously, ensure you follow the other Telly instructions in the readme.

**Comment by KunfuMunky** [comment]
@diswell yeah I thought you meant that. I was already able to find the files via SSH but I don't know the command to run the file. Can you help me with that?

**Comment by diswell** [comment]
./telly [then add the various parameters listed in the readme file]

**Comment by KunfuMunky** [comment]
@diswell di you saw the command because nothing is happening...

**Comment by diswell** [comment]
If you've copied Telly to the NAS, you've copied the .m3u file from your IPTV provider to the same folder, you can SSH into the NAS and navigate to that same folder, then you should be good to go with the developer's instructions. That all I can help you with at this point.

**Comment by diswell** [comment]
Two more thoughts:

1. Be sure to change the file name to whatever is in your command. i.e. when you download the file, it'll be "telly-blah-blah". Change it to "telly" then copy it across to the NAS before trying to run it with ./telly

2. If you get a permission denied error when trying to run the file, you need to change its permissions. In your SSH window, navigate to the folder with telly and run this command:

chmod 766 * -R

**Comment by dpohlman** [comment]
Ok, I know telly is for plex, but with the complications of matching up guide data, do you think there would be any way to make this work for Emby as well.  They already have an m3u tuner that lets you put in your own xml guide data url, but they don't have any way of filtering all then unwanted channels.  Emby also has the ability to use HDhomerun and have xml data, so I was kind of hoping telly would just work with Emby as well.  But alas it does not detect the "simulated" HDhomerun from telly the same way Plex does.

**Comment by 12nick12** [comment]
Why would you want it for Emby? I tried to manually add it to Emby a couple versions ago before I realized they had a m3u tuner and didn't have any luck. For filtering I just made a script that greps the main m3u from Vaders with only the channels I want and puts those in a file for me. I point telly and Emby to that m3u.

**Comment by 12nick12** [comment]
Heres the script I put together. My OS is Debian. Hopefully it makes sense. The site is safe, its just a cheap domain I purchased. https://up.5link.cc/ietxojb3.file

You might be able to get away with just using normal grep. The reason I did egrep was because I used to search for a different field, but since I switched it to the tvg-id I don't think it needs to be as messy.

**Comment by dpohlman** [comment]
Many thanks, amazing our similar taste in pruned channels!

**Comment by 12nick12** [comment]
NP and yeah lol. Pretty everything that's not sports is what I like.

**Comment by tombowditch** [comment]
Okay. Going through these one by one from the 28th Feb.

-------------------------

@dqans is this Plex related?

---------------------

@ioan-rosca can you open an issue regarding Synology?

--------------------------

@KunfuMunky @maekillam can you guys open an issue regarding QPKG/QNAP? I am unfamiliar with it, but would be able to look into it :)

-------------------------

@dpohlman Emby is already "supported" per say, I know people have it working. You can use the `-useregex` parameter to filter out your list, or are you looking for something different?

------------------------

Thanks all!

**Comment by tombowditch** [comment]
I'm going to close + lock this issue now as it's against the whole "open one issue per suggestion/issue" thought - **this isn't me not accepting suggestions, if you want something added to telly, please OPEN AN ISSUE!**

Thanks all!
