### ISSUE TITLE
cannot determine available commands for telly

### ISSUE THREAD

**Issue by compkickers** [tombowditch/telly#70]
Is there any documentation for telly?? Mainly some sort of command list and short desc of what commands do.

great tool though, its made my day.

Just wish i could work out best way to use it and work around issues im having like channel quantity issues?

Thanks

**Comment by HazCod** [comment]
What about ‘./telly -help’?

**Comment by compkickers** [comment]
Is it the same on the Windows versions???

 

Ill try it, I did try but not sure if I tried -help

**Comment by haxcop** [comment]
@compkickers Hi - you can use '--help' for more information

**Comment by haxcop** [comment]
Hi @compkickers you can run multiple instances of Telly  groups or channels in many ways... 
for Example: here you can see for command 1 only for sports groups and 2 for Channels - 

> 1
`telly-windows-amd64.exe -playlist="Path.to.your.file.M3U"  -friendlyname "Sports" -useregex 'Sports' -deviceid "00000001" -listen "127.0.0.1:1077"`

> 2
``telly-windows-amd64.exe -playlist="Path.to.your.file.M3U"  -friendlyname "Channels" -useregex 'ABC|Fox'-deviceid "00000002" -listen "127.0.0.1:2077"``

So From here you can now use two DVRs one in 127.0.0.1:1077 and the second on 127.0.0.1:2077

So have Fun and Try as many as you can try--

BTW if the Groups and Channels are into the same country i'll recommend you use the Plex EPG and map the channels with him., IF not please use the EPG.xml Provided by your iptv provider. 
After your have done all of them - Restart your Plex

**Comment by tombowditch** [comment]
@compkickers correct - lots of us have over 420 channels in our m3u's, but lots of us also filter is down using the regex. @haxcop is correct that you can use multiple instances. Just to note: when changing the friendly names or device ID's it's a wise idea to restart plexmediaserver as it tends to do alot of caching.

The 420 channel thing is, unfortunately, completely out of telly's control as it's purely a Plex issue.

T

**Comment by compkickers** [comment]
@tombowditch yeah i did try to filter my m3u down but even then i was coming up with over 450, but now i know i can create multiple streams each with a seperate m3u my problem is solved.

Keep up the good work,

JK

**Comment by HazCod** [comment]
Closing since the question has been answered.

**Comment by chazlarson** [comment]
Depending on the version you are running there is either a new flag that takes the place of -playlist [    --iptv.playlist="iptv.m3u" in version 1.0.1], or telly uses a config file [1.1].  If `telly.exe --help` does not show any playlist-related flags, then you're running the config-file version.

**Comment by owengrey** [comment]
Thanks chazlarson, Im a noob at this as just getting started in this amazing topic. I have got got telly running but not getting plex to recognise telly. Looks like I have got a lot of reading to do.
