### ISSUE TITLE
Telly on ubuntu.

### ISSUE THREAD

**Issue by Sheryars** [tombowditch/telly#71]
I'm very new to ubuntu. Can someone guide me how to install telly on Ubuntu.

**Comment by tombowditch** [comment]
Hi,

What part are you stuck at/do you need help with?

**Comment by Sheryars** [comment]
i got it working. read through the discord messages where you guided someone. 

I am stuck trying to sort out epg now since i have multiple countries links from the m3u file.

**Comment by Sheryars** [comment]
can you help me run telly by default in the background. at the moment i have to run it through the terminal in ubuntu

**Comment by HazCod** [comment]
This is unrelated to telly. Please get help in your respective ubuntu forum/channel.

Besides.. `./telly -playlist=myplaylist &`
