### ISSUE TITLE
implement persistent channel numbers

### ISSUE THREAD

**Issue by programmerq** [tombowditch/telly#72]
Currently, channels are numbered incrementally which can introduce an issue where the channels shift if the regex changes.

While some providers to provide tvg-id fields to determine a channel number, it isn't a ubiquitous piece of information across all providers.

It would be preferable to have a given channel have a consistent channel number despite changes to the total list of channels available over time.

Possible implementations might include a modulo or checksum operation to provide a reliable channel name->number mapping, or a name->number mapping that would need to be persisted to disk in a file or database.

**Comment by tombowditch** [comment]
Definitely will use this as a fallback to #67

**Comment by HazCod** [comment]
Closing this, please continue discussion in https://github.com/tombowditch/telly/issues/63
