### ISSUE TITLE
Not working on Docker/Synology

### ISSUE THREAD

**Issue by vdias** [tombowditch/telly#75]
Trying to execute this on my Synology NAS using docker... and it doesn't work. 

Any build available to run it directly on Synology/Xpenology without docker?

**Comment by tombowditch** [comment]
Got any more information other than "it doesn't work"? Any logs?

**Comment by HazCod** [comment]
How did you specify your playlist?

**Comment by vdias** [comment]
did not reach that step... deploy docker image... and it just keep on reboot... imposible to change anything...

**Comment by HazCod** [comment]
Err, I believe you don’t know how to use Docker then.
Telly expects the playlist parameter to be given. When using Docker, this has to be given as an argument.

Because you’re not supplying one, the process exits and the container stops running. It says exactly that in the logs. (Playlist file not found)

**Comment by vdias** [comment]
do i need to map some folder? or just point the m3u file?

**Comment by HazCod** [comment]
Depends whether the file is reachable on the internet using an URL or only locally.
If it's local, you will need to map a folder.

**Comment by vdias** [comment]
On synology docker... i can map a folder or change variable... but as you can see telly.m3u is already defined on docker image... 

![telly02](https://user-images.githubusercontent.com/2320553/37678869-9400e680-2c7f-11e8-8fb3-e8b722eb3e24.PNG)
![telly01](https://user-images.githubusercontent.com/2320553/37678870-946ace60-2c7f-11e8-8ae4-f7f0cea2be70.PNG)

The m3u is locally on my nas...

**Comment by vdias** [comment]
![telly03](https://user-images.githubusercontent.com/2320553/37679078-33b2cb6c-2c80-11e8-87de-33cb12414e64.PNG)
Trying to point to my m3u i cannot even deploy the container...

**Comment by HazCod** [comment]
You didn’t mount /TV/ ?

**Comment by vdias** [comment]
i canot create the container... error about "command"

**Comment by HazCod** [comment]
I'm going to close this. Please get help with Docker or Synology on their respective forums, telly works fine.
