### ISSUE TITLE
Specify Group Titles

### ISSUE THREAD

**Issue by theflu** [tombowditch/telly#76]
I would like to be able specify groups tiltles so it only pulls those from the m3u
group-title="something here"

Ex:
-group-titles 'us|ca|uk' # this would pull every this with us, ca and uk as group title

**Comment by HazCod** [comment]
I understand the need, problem is that groups actually are a made up thing in M3Us.
They are just channels

**Comment by theflu** [comment]
What if you parse the m3u as text file and remove the no matching entries and save the new m3u in tmp

**Comment by theflu** [comment]
I wrote this script to do it

`#!/usr/bin/python3.5
import os
import sys
import string
import requests

m3u_url = 'http://something.com'
var_name = 'group-title'
var_options = ['United States']
save_file = 'playlist.m3u'

req = requests.get(m3u_url)

req_text = req.text

lines = req_text.splitlines()

with open(save_file, 'w') as m3u_file:
  i = 0
  match = False
  for line in lines:
    if i == 0:
      if line != '#EXTM3U':
        print("Not valid M3U file")
        sys.exit()
      m3u_file.write('#EXTM3U')
      m3u_file.write("\n")
      m3u_file.write("\n")

    if match:
      m3u_file.write(line)
      m3u_file.write("\n")
      m3u_file.write("\n")
      match = False

    if line.startswith('#EXTINF'):
      split_line = line.split(var_name+'="')
      split_line = split_line[1].split('"')
      if split_line[0] in var_options:
        m3u_file.write(line)
        m3u_file.write("\n")
        match = True

    i = i+1`

**Comment by smromain** [comment]
For this particular situation, I actually just use the internal `-useregex` flag: `-useregex="(group-title(.*)United States|group-title(.*)Sports|Premium Movies)"`

If this functionality is wanted, I'm happy to do a PR for something like, `-grouptitles` which does something similar underneath the hood as a simple convenience method? Been wanting to get involved with this project for a bit now ;)
