### ISSUE TITLE
Lost

### ISSUE THREAD

**Issue by duderz2011** [tombowditch/telly#78]
i am so lost ive downloaded the windows file and am using CMD and following the the tutorials but im getting nothing. am i in the wrong place completely?

**Comment by Latiron** [comment]
Hey bud, swing over to the Discord group for telly and there are several of us who would be happy to help you out.

**Comment by duderz2011** [comment]
where do i find this group?

**Comment by haxcop** [comment]
@duderz2011 is in the first-page README at the bottom line >> https://discord.gg/bnNC8qX
