### ISSUE TITLE
[Question/Feature request] Using Telly to connect enigma2/BH to Plex Live

### ISSUE THREAD

**Issue by giopas** [tombowditch/telly#81]
Is it/will it be possible to use Telly as a "bridge" to stream/pass along (standard and/or IPTV) channels from an enigma2/Black Hole device to Plex Live & DVR?

**Comment by HazCod** [comment]
If the enigma2/black hole device offer M3U playlist files to stream like IPTV, sure.

**Comment by giopas** [comment]
If you open the WebUI (openwebif) of the Black holes, you can select a Bouquet and clicking on the TV icon, you can download an m3u8 file starting like the following:

#EXTM3U
#EXTVLCOPT-http-reconnect=true
#EXTINF:-1,CCN
#EXTVLCOPT: program=3023
http://192.168.1.23:8001/1:0:1:D3B:1867:4BH:FGTT:820000:0:0:0:

Is that something that Telly can understand?

Thanks!

**Comment by HazCod** [comment]
If you can open that URL in VLC and it plays fine, yes.

**Comment by AllviewTV** [comment]
You could use the Plex DVR plugin on your enigma2 device and set it up on plex normal set up works perfect for me

**Comment by giopas** [comment]
@HazCod I have tried, but it seems that it does not work.

@AllviewTV googling I see that Plex DVR is now called HRTunerProxy [1], but I do not know how to install it and how to use it. cAn you please provide some additional information/guidance?

Thanks.

ps: this way Telly is not even necessary, right?

[1] https://github.com/OpenViX/HRTunerProxy

**Comment by HazCod** [comment]
Closing the issue as this isn't telly related, but feel free to continue the discussion.
