### ISSUE TITLE
Unable to tune channel (Timed out)

### ISSUE THREAD

**Issue by lordbeavis** [tombowditch/telly#82]
i am using eternaltv and i can filter the channel list and load the container with the docker, plus add it to plex and get the epg downloaded, but when i go to watch an channel it says "Unable to tune channel (Timed out)"

i am using docker and telly 0.5

**Comment by HazCod** [comment]
Can you provide your full telly logs and mask your IPTV urls?

**Comment by lordbeavis** [comment]
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv,
[telly] [info] listening on 0.0.0.0:6077,
[telly] [info] creating device xml,
[telly] [info] Building lineup,
[telly] [info] creating webserver routes,
[telly] [info] creating lineup status,
[telly] [info] found 211 channels,
[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels,
[telly] [info] Reading m3u file /telly.m3u...,
[telly] [info] creating discovery data,
[telly] [info] Downloading file http://live.eternaltv.net:25461/get.php?username=USERNAME&password=PASSWORD&type=m3u_plus&output=ts to /telly.m3u,[telly] [info] booting telly v0.5

**Comment by HazCod** [comment]
Did you try opening your `http://live.eternaltv.net...` URL with VLC to check if it works?
Also, what are your arguments you pass to telly?

**Comment by lordbeavis** [comment]
this is what i get from vlc:
Your input can't be opened:
VLC is unable to open the MRL 'http://live.eternaltv.net:25461/movie/USERNAME/RPASSWORD/25701.mp4'. Check the log for details.
But then it plays a movie

my arguments are:
docker run \
  -d \
  --name telly \
  -p 6077:6077/tcp \
  -v /home/lbeavisc/appdata/telly/tmp:/tmp \
  -e PLAYLIST="http://live.eternaltv.net:25461/get.php?username=USERNAME&password=PASSWORD&type=m3u_plus&output=ts" \
  -e USEREGEX="USA|USA-PREMIUM MOVIE" \
  -e STREAMS=1 \
  -e FRIENDLYNAME="Tuner1" \
  -e DEVICEID="12345" \
  -e TEMP=/tmp \
tombowditch/telly

**Comment by HazCod** [comment]
So you are able to tune to the channel in VLC you tried in Plex?

Also, is that the complete log? I do not see any request from Plex to telly.

**Comment by lordbeavis** [comment]
{"log":"[telly] [info] booting telly v0.5\n","stream":"stdout","time":"2018-04-16T08:00:07.244401431Z"}
{"log":"[telly] [info] Downloading file http://live.eternaltv.net:25461/get.php?username=USERNAME\u0026password=PASSWORD\u0026type=m3u_plus\u0026output=ts to /tel$
{"log":"[telly] [info] Reading m3u file /telly.m3u...\n","stream":"stdout","time":"2018-04-16T08:00:07.487374001Z"}
{"log":"[telly] [warning] telly is not attempting to strip out unneeded channels, please use the flag -filterregex if telly returns too many channels\n","stream":"s$
{"log":"[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv\n","stream":"stdout","time":"2018$
{"log":"[telly] [info] found 211 channels\n","stream":"stdout","time":"2018-04-16T08:00:07.509357424Z"}
{"log":"[telly] [info] creating discovery data\n","stream":"stdout","time":"2018-04-16T08:00:07.509362386Z"}
{"log":"[telly] [info] creating lineup status\n","stream":"stdout","time":"2018-04-16T08:00:07.509366809Z"}
{"log":"[telly] [info] creating device xml\n","stream":"stdout","time":"2018-04-16T08:00:07.509371389Z"}
{"log":"[telly] [info] creating webserver routes\n","stream":"stdout","time":"2018-04-16T08:00:07.509375951Z"}
{"log":"[telly] [info] Building lineup\n","stream":"stdout","time":"2018-04-16T08:00:07.509380773Z"}
{"log":"[telly] [info] listening on 0.0.0.0:6077\n","stream":"stdout","time":"2018-04-16T08:00:07.509773782Z"}

**Comment by lordbeavis** [comment]
i got it working

docker run \
  -d \
  --name telly \
  -p 6077:6077/tcp \
  -v /home/lbeavisc/appdata/telly/tmp:/tmp \
  -e PLAYLIST="http://live.eternaltv.net:25461/get.php?username=USERNAME&password=PASSWORD=m3u_plus&output=ts" \
  -e USEREGEX="USA|USA-PREMIUM MOVIE" \
  -e STREAMS=1 \
  -e FRIENDLYNAME="Tuner1" \
  -e DEVICEID="12345678" \
  -e TEMP="/tmp" \
  -e PUID=1000 \
  -e PGID=1000 \
  -e LISTEN=172.17.0.11:6077 \
tombowditch/telly

i added the puid and pgid and quotes on the temp dir and added the docker container ip
