### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by bevanpfc** [tombowditch/telly#83]
Hi Tom, just a quick hypothetical question for you, as telly tricks plex into thinking it’s a HDhomeRun could the same practice be done so that this 3rd party HDhomeRun app could work with Telly ?

https://getchannels.com/

**Comment by HazCod** [comment]
This should theoretically work!

**Comment by bevanpfc** [comment]
Yeah, I’d be interested to try it but the app on tvOS is almost $30 !
They have an api available in the support section on their website, not sure if that would help you guys out.
EPG shouldn’t be a problem as far as I can see as it seems to support multi countries.

**Comment by bevanpfc** [comment]
So I took the risk and bought the channels app purely out of curiosity!
I have the option to manually add tuner so I’m guessing I should enter the IP address of my Mac that I’m using telly on.
Entering this gives me an error “no tuner could be found”
I’ve tried adding the port number as well but that doesn’t work either, not sure if I’m entering it right 192.xxx.x.xx:6077

So at the moment it doesn’t look like this app will work or maybe I’m not entering the right details in the manual tuner settings.

**Comment by HazCod** [comment]
You could perhaps try to run a tcpdump on your mac (`sudo tcpdump -s0 -w $(whoami)/Desktop/telly.pcap`), try adding the tuner and see what's in the packet capture.
(Or upload it for me to check)

**Comment by HazCod** [comment]
It seems Channels wants the SSDP UDP stuff to work for discovery, which is tracked here: https://github.com/tombowditch/telly/pull/48

**Comment by tmm1** [comment]
Channels does not use SSDP, but expects the HDHomeRun-specific UDP control/discovery API to be implemented on port 65001

**Comment by HazCod** [comment]
Ahh, I thought those were the same.

**Comment by myusuf3** [comment]
@maddox

**Comment by HazCod** [comment]
Merged to master, please build from the repo or wait for the next release.

**Comment by tombowditch** [comment]
SSDP support is built and in from telly v0.6

**Comment by myusuf3** [comment]
does this mean it works with channels now?

**Comment by radge** [comment]
No, Channels still doesn’t recognise telly for me.
