### ISSUE TITLE
There was a transcoder error

### ISSUE THREAD

**Issue by a8ree** [tombowditch/telly#84]
Hi

I'm running Plex server on 2012 R2 and I set up Telly without issue (x64) and did the channel mappings. When trying to record I get 
'There was a transcoder error'

I see the following in the Plex logs

Apr 18, 2018 22:27:11.809 [166496] DEBUG - Cleaning directory for session pbkoizh342qdbu68hv8lucoe (C:\Temp\Transcode\Sessions\plex-transcode-pbkoizh342qdbu68hv8lucoe-da77b312-e887-4971-b29a-749d7ba07399)
Apr 18, 2018 22:27:11.810 [166496] DEBUG - Cleaning directory for session pbkoizh342qdbu68hv8lucoe (C:\Temp\Transcode\Sessions\plex-transcode-pbkoizh342qdbu68hv8lucoe-322704bd-fcf7-4787-9e30-d0ff87f78a63)
Apr 18, 2018 22:27:14.041 [140400] DEBUG - Activity: updated activity ba2d9f8e-2514-4465-9fa1-7bc8d7d1d651 - completed 1% - Recording
Apr 18, 2018 22:27:17.043 [166496] DEBUG - Activity: updated activity ba2d9f8e-2514-4465-9fa1-7bc8d7d1d651 - completed 2% - Recording
Apr 18, 2018 22:27:17.279 [242196] ERROR - [Transcoder] Option scan_all_pmts not found.
Apr 18, 2018 22:27:17.285 [140400] DEBUG - Jobs: 'C:\Program Files (x86)\Plex\Plex Media Server\PlexTranscoder.exe' exit code for process 241420 is 1

Any suggestions how to resolve this?

**Comment by a8ree** [comment]
And some more of the log

Apr 18, 2018 22:30:30.866 [166496] DEBUG - DVR:Grabber: Setting timer to stop grab of 'Live TV - Session' in 300 seconds.
Apr 18, 2018 22:30:30.867 [166496] DEBUG - DVR:Grabber: Waiting for a tuner (2 available).
Apr 18, 2018 22:30:30.867 [166496] DEBUG - DVR:Grabber: Allocated a tuner (1 left)
Apr 18, 2018 22:30:30.868 [166496] DEBUG - We're going to try to auto-select an audio stream for account 1.
Apr 18, 2018 22:30:30.868 [166496] DEBUG - Selecting best audio stream for part ID -1 (autoselect: 1 language: en)
Apr 18, 2018 22:30:30.868 [1964] DEBUG - Completed: [127.0.0.1:54648] 200 GET /media/subscriptions/scheduled (18 live) GZIP 5ms 2284 bytes (pipelined: 3)
Apr 18, 2018 22:30:30.869 [166496] DEBUG - Audio Stream: -1, Subtitle Stream: -1
Apr 18, 2018 22:30:30.870 [166496] DEBUG - MDE: Selected protocol hls; container: mpegts
Apr 18, 2018 22:30:30.870 [166496] ERROR - Unable to find title for item of type 5
Apr 18, 2018 22:30:30.870 [166496] DEBUG - MDE: analyzing media item -1
Apr 18, 2018 22:30:30.870 [166496] DEBUG - MDE: : no direct play video profile exists for http/mpegts/
Apr 18, 2018 22:30:30.871 [166496] DEBUG - MDE: : no direct play video profile exists for http/mpegts//
Apr 18, 2018 22:30:30.871 [166496] DEBUG - MDE: : codec is unavailable for analysis
Apr 18, 2018 22:30:30.871 [166496] DEBUG - MDE: : codec is unavailable for analysis
Apr 18, 2018 22:30:30.871 [166496] ERROR - Unable to find title for item of type 5
Apr 18, 2018 22:30:30.872 [166496] DEBUG - MDE: : selected media 0 / -1
Apr 18, 2018 22:30:30.872 [166496] DEBUG - Cleaning directory for session 6ea1e309-285b-464b-9b30-65708c853001 ()
Apr 18, 2018 22:30:30.873 [166496] DEBUG - Starting a transcode session 6ea1e309-285b-464b-9b30-65708c853001 at offset -1.0 (state=3)
Apr 18, 2018 22:30:30.874 [166496] DEBUG - Streaming Resource: Added session 0xbc22728:6ea1e309-285b-464b-9b30-65708c853001
Apr 18, 2018 22:30:30.881 [166496] DEBUG - Job running: EAE_ROOT='\\?\C:\Temp\Transcode\Sessions\EasyAudioEncoder' FFMPEG_EXTERNAL_LIBS='\\\\?\\C\:\\Users\\a8ree.MICRO2\\AppData\\Local\\Plex\ Media\ Server\\Codecs\\7814ac9-1285-windows-i386\\' XDG_CACHE_HOME='C:\Users\a8ree.MICRO2\AppData\Local\Plex Media Server\Cache\' XDG_DATA_HOME='C:\Program Files (x86)\Plex\Plex Media Server\Resources\' X_PLEX_TOKEN='xxxxxxxxxxxxxxxxxxxx' C:\Program Files (x86)\Plex\Plex Media Server\PlexTranscoder.exe -noaccurate_seek -ignore_unknown -scan_all_pmts -1 -rw_timeout 30000000 -fflags +discardcorruptts+fillwallclockdts -i http://localhost:6077/stream/aHR0cDovL3ZhcGkudmFkZXJzLnR2L3BsYXkvMzk4MzcubTN1OD90b2tlbj1leUoxYzJWeWJtRnRaU0k2SW1FNGNtVmxJaXdpY0dGemMzZHZjbVFpT2lKQllVSmlRMk16T1RneE1DSjk=?transcode=heavy -map 0:V? -codec:V copy -map 0:a? -codec:a copy -copypriorss:a 0 -map 0:s? -codec:s copy -segment_format mpegts -f ssegment -individual_header_trailer 0 -segment_time 1 -segment_start_number 0 -segment_time_delta 0.0625 -segment_list http://127.0.0.1:32400/video/:/transcode/session/6ea1e309-285b-464b-9b30-65708c853001/cd55ec5d-92db-4cf7-9491-562b1152063e/seglist -segment_list_type csv -segment_list_size 2147483647 -segment_list_separate_stream_times 1 -max_delay 5000000 -map_metadata -1 -map_chapters -1 media-%05d.ts -y -nostats -loglevel quiet -loglevel_plex error -progressurl http://127.0.0.1:32400/video/:/transcode/session/6ea1e309-285b-464b-9b30-65708c853001/cd55ec5d-92db-4cf7-9491-562b1152063e/progress 
Apr 18, 2018 22:30:30.907 [1964] DEBUG - Completed: [127.0.0.1:54647] 200 GET /media/subscriptions (18 live) GZIP 41ms 2299 bytes (pipelined: 3)
Apr 18, 2018 22:30:33.852 [218500] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 1% - Recording
Apr 18, 2018 22:30:36.854 [222196] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 2% - Recording
Apr 18, 2018 22:30:36.896 [240692] ERROR - [Transcoder] Option scan_all_pmts not found.
Apr 18, 2018 22:30:36.902 [139676] DEBUG - Jobs: 'C:\Program Files (x86)\Plex\Plex Media Server\PlexTranscoder.exe' exit code for process 247668 is 1
Apr 18, 2018 22:30:39.198 [1964] DEBUG - handleStreamRead code 335544539: short read
Apr 18, 2018 22:30:39.202 [1964] DEBUG - Auth: authenticated user 1 as a8ree
Apr 18, 2018 22:30:39.203 [248740] DEBUG - Request: [192.168.1.239:50252 (Allowed Network)] GET /player/proxy/poll?deviceClass=pc&protocolVersion=1&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (16 live) TLS GZIP Signed-in Token (a8ree)
Apr 18, 2018 22:30:39.204 [248740] DEBUG - Beginning read from two-way stream.
Apr 18, 2018 22:30:39.855 [222196] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 3% - Recording
Apr 18, 2018 22:30:42.855 [140400] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 4% - Recording
Apr 18, 2018 22:30:45.856 [218500] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 5% - Recording
Apr 18, 2018 22:30:48.857 [222196] DEBUG - Activity: updated activity 2f6f8dc1-98c9-46e4-8df9-5d22a3cbc7ca - completed 6% - Recording
Apr 18, 2018 22:30:49.208 [1964] DEBUG - handleStreamRead code 995: The I/O operation has been aborted because of either a thread exit or an application request
Apr 18, 2018 22:30:49.208 [1964] WARN - LongPoll: Got error, closing.

**Comment by a8ree** [comment]
Sorry, where are they located/ what are they called?

**Comment by a8ree** [comment]
here is the window output

[telly] [info] booting telly v0.5
[telly] [info] Reading m3u file Z:\ServerFolders\ServerApps\scripts\vget.m3u...
[telly] [warning] telly is not attempting to strip out unneeded channels, please
 use the flag -filterregex if telly returns too many channels
[telly] [info] telly is currently not filtering for only uk television. if you w
ould like it to, please use the flag -uktv
[telly] [info] found 30 channels
[telly] [info] creating discovery data
[telly] [info] creating lineup status
[telly] [info] creating device xml
[telly] [info] creating webserver routes
[telly] [info] Building lineup
[telly] [info] listening on localhost:6077
[telly] [request] 127.0.0.1:60713 -> GET /lineup.json
[telly] [request] 127.0.0.1:60721 -> GET /stream/aHR0cDovL3ZhcGkudmFkZXJzLnR2L3B
sYXkvMzkwMjgubTN1OD90b2tlbj1leUoxYzJWeWJtRnRaU0k2SW1FNGNtVmxJaXdpY0dGemMzZHZjbVF
pT2lKQllVSmlRMk16T1RneE1DSjk=?transcode=heavy
[telly] [debug] Parsing URI /stream/aHR0cDovL3ZhcGkudmFkZXJzLnR2L3BsYXkvMzkwMjgu
bTN1OD90b2tlbj1leUoxYzJWeWJtRnRaU0k2SW1FNGNtVmxJaXdpY0dGemMzZHZjbVFpT2lKQllVSmlR
Mk16T1RneE1DSjk=?transcode=heavy to aHR0cDovL3ZhcGkudmFkZXJzLnR2L3BsYXkvMzkwMjgu
bTN1OD90b2tlbj1leUoxYzJWeWJtRnRaU0k2SW1FNGNtVmxJaXdpY0dGemMzZHZjbVFpT2lKQllVSmlR
Mk16T1RneE1DSjk=
[telly] [debug] Redirecting to: http://vapi.vaders.tv/play/39028.m3u8?token=eyJ1
c2VybmFtZSI6ImE4cmVlIiwicGFzc3dvcmQ0OiJBYUJiQ2MzOTgxMCJ9

**Comment by nakure** [comment]
@a8ree that final URL for vapi.vaders includes your token, so that can be piped into any of their channel m3us to watch tv using your account.  You should update your password with vaders to renew your token.

**Comment by HazCod** [comment]
Weird thing is, your encoded URL decodes to a string with unicode characters. What kind of keyboard setting do you use?

**Comment by HazCod** [comment]
Closing since there is no feedback.. Feel free to reopen this.
