### ISSUE TITLE
Complete noob

### ISSUE THREAD

**Issue by MentulTH** [tombowditch/telly#86]
I'm a complete noob to this. I have Plex, a NVDIA Shield and an IPTV suh. Can you please help or post a video tutorial? Never really messed with Plex aside from the DLNA side of it for a private VoD library. TiA

**Comment by MentulTH** [comment]
Meant to say IPTV sub

**Comment by HazCod** [comment]
Is plex running on the NVIDIA Shield or windows/mac/linux?
The main idea is to run telly as `./telly -playlist=path-to-your-m3u.m3u` and set it up as `ip-of-pc-running-telly:6077` in Plex as a DVR.

**Comment by dopke139** [comment]
@HazCod **"and set it up as ip-of-pc-running-telly:6077 in Plex as a DVR."** - have you managed to configure it this way? I'm trying but even with windows firewall off on both ends Plex won't see Telly. Only way I can get it to work is running telly on the same machine as Plex.

**Comment by HazCod** [comment]
This does work as intended:

```
~$ touch test && ./telly -listen=0.0.0.0:6077 -playlist=test
.... telly runs ...

~$ lsof -nP -i4TCP:6077 | grep LISTEN
telly   743 <user>    3u  IPv6 0x39d3170d1d6f7f99      0t0  TCP *:6077 (LISTEN)

```

**Comment by HazCod** [comment]
No problem, when in doubt use ‘-help’.

**Comment by TomGlass** [comment]
I'd recommend using the docker file given what you've told me
