### ISSUE TITLE
Specific Formats

### ISSUE THREAD

**Issue by cibrd0wn** [tombowditch/telly#87]
I have Telly 0.5.0 installed on my qnap nas. If i try to run telly -playlist=http://api.vaders.tvXXXXXX.ts I get _[error] Could not create file: /opt/tmp ; open /opt/tmp: is a directory._

**If i try to run telly -playlist=/Public/iptv.m3u** I get Reading m3u file /Public/iptv.m3u...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file_

I have verified unix ends and UTF-8 encoding 

Any help would be great.

**Comment by HazCod** [comment]
Can you try with `./telly -playlist=<..> -temp=/tmp/` ?

**Comment by HazCod** [comment]
Closing this since no feedback, feel free to reopen.
