### ISSUE TITLE
vaders IPTV

### ISSUE THREAD

**Issue by grdon999** [tombowditch/telly#88]
Hi, If I use tvheadend and the proxy I can use my vaders IPTV. If I use telly I get cannot tune to channel all the time. I can use telly with other IPTV, and I think it is due to vaders redirecting the stream, so when you look at the url that telly gets and open that url it downloads another file in the following format 

#EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=25.000,CODECS="avc1.64001f,mp4a.40.2",AVERAGE-BANDWIDTH=2010026,BANDWIDTH=2512532
tracks-v1a1/mono.m3u8?token=*** I have removed the token for this post ***

and this just does not play. When I look at plex processes it does not even try to transcode. I have tried telly with and without the -direct option but no difference. Any ideas?

**Comment by HazCod** [comment]
I’m afraid telly doesn’t support playlists for the streams themselves for now

**Comment by grdon999** [comment]
so does that mean there is no way to use vader iptv wwith telly?

**Comment by HazCod** [comment]
Just to confirm, you have m3uplus with mpegts selected when downloading your m3u playlist, right?

**Comment by grdon999** [comment]
So I am using 

http://api.vaders.tv/vget?username=xxxxx&password=xxxxx&type=m3u_plus&output=ts

but that still seems to get the EXT-X-STREAM file. So when i look in /tmp at the telly m3u file and wget one of the urls from there I dont get the ts stream I get this oher file

**Comment by grdon999** [comment]
is anyone using vaders stream with telly? Other posts on github seem to suggest they are

**Comment by grdon999** [comment]
ok So I have found that if you use format=ts rather than output=ts you get a stream that telly likes.
