### ISSUE TITLE
Telly on QNAP

### ISSUE THREAD

**Issue by b1ll0t0s** [tombowditch/telly#89]
Hi, I am new to this effort and I love telly and how it works. I apologize if my question is stupid but I am trying to see how telly can remain open after I terminate my shh session in qnap.

I was able to edit my iptv m3u playlist to include only a very few channels so it's easier for telly to load and I was able to see the tv guide for the channels on plex. Everything works as expected but how can I close the ssh session and still keep telly running on my qnap and plex? 

I did some online research, tried using tmux or other ssh commands but once I close my ssh window telly terminates and live IPTV on plex stops working.

Any suggestions? Again I apologize if this has been answered before but I'm not an expect in this field.

Thanks!

**Comment by HazCod** [comment]
Try writing a init.d or systemd file for it, so it runs as a service and is restarted when it fails.

An easy way: ‘ssh server “telly -playlist=file &”

**Comment by HazCod** [comment]
Closing this as this is unrelated to telly.
