### ISSUE TITLE
Mac OS support?

### ISSUE THREAD

**Issue by Davrizio** [tombowditch/telly#9]
Hey! This is great! How would I go about this on Mac OS? Or is it not possible currently?

**Comment by tombowditch** [comment]
Hey,

macOS support is available! The one you'll be needing is Darwin amd64: https://github.com/tombowditch/telly/releases/tag/v0.2

T

**Comment by Davrizio** [comment]
Thanks man! That’s what I thought! Okay so how do I go about running? The system recognizes the downloaded file as a text file and when I try to run it via terminal I get “permission denied”. 
Sorry for the noob questions. :-)

**Comment by HazCod** [comment]
Try a ‘chmod +x <telly-filename-here>’ before running to make it executable.

**Comment by Davrizio** [comment]
Ahh yes! Thanks so much!
