### ISSUE TITLE
Debian/Ubuntu install

### ISSUE THREAD

**Issue by trantoriana** [tombowditch/telly#92]
Hi,

I must be either very stupid today, or did not have enough coffee, but how do I install telly on ubuntu server ?

dpkg always complains that (any) of the install packages are not in debian format.
Which install should I take for OS : 16.04 LTS (GNU/Linux 4.15.15-1-pve x86_64)

Thanks, Tran

==================
sudo dpkg -i telly-linux-amd64
dpkg-deb: error: 'telly-linux-amd64' is not a debian format archive
dpkg: error processing archive telly-linux-amd64 (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 telly-linux-amd64

**Comment by trantoriana** [comment]
Never mind, I build from source....

**Comment by HazCod** [comment]
( we provide the binaries and not installation packages. So download the appropriate one and make it executable with chmod. )
