### ISSUE TITLE
allow multiple instances to run on the same server

### ISSUE THREAD

**Issue by boo0ger** [tombowditch/telly#94]
My intention is to split the telly.exe into instances so that I can use the built in EPG features from Plex (using the location features).

i.e. 
Telly (id:00000001) Friendlyname="Telly-Canada" regex="Canada" listen="localhost:6001" 
Telly (id:00000002) Friendlyname="Telly-USA" regex="United States" listen="localhost:6002" 
Telly (id:00000003) Friendlyname="Telly-UK" regex="United Kingdom" listen="localhost:6003" 

Unfortunately, this didn't work. The first instance (Canada) shows 49 channels, but the rest shows up as running, but are blank (and not listening to the port).  

fyi, I also created a separate temp file for each. (i.e. temp="....\telly-canada.m3u")

**Comment by boo0ger** [comment]
Ok I managed to run three distinct instances although Plex kept confusing the friendly-names even if they were correctly configured.  Also Plex didn't allow me to choose a different "tv provider" even if it allows me to seleft a different country.... So unfortunately my plans didn't work out too well :/

**Comment by HazCod** [comment]
Sorry to hear that, feel free to comment on this issue if you find a way to make it work!
