### ISSUE TITLE
Support stream m3u8 playlists

### ISSUE THREAD

**Issue by kla1989** [tombowditch/telly#95]
Would it be possible to use IPTV with .m3u8 streams and not .ts?
Then it would be possible to use IPTV of free channels, like the german public law channels providing there livestreams.

for example: 
- https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/

- https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/clean/clean_tv_main.m3u

format of IPTV inside list, e.g.:
https://daserstelive-lh.akamaihd.net/i/daserste_de@38086/index_2692_av-p.m3u8

Would be cool to get that working
Kind regards

**Comment by EnorMOZ** [comment]
Plex has either stopped supporting m3u8 or it is a bug in a recent version of plex.

**Comment by tombowditch** [comment]
As @EnorMOZ said, Plex (from what I can see here) is no longer supporting `.m3u8` files.

Working on a solution involving ffmpeg/transcoding to `.ts` so Plex will stream it.

**Comment by tombowditch** [comment]
#115
