### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by ElBrad** [tombowditch/telly#96]
I've had telly running with Plex for the last few days, but most of the time when I record something I get only a few minutes to 40 mins of a 1 hour program. I'm not sure if this is a Plex issue or an issue with telly. I'm guessing the signal gets cut and telly or Plex doesn't recover and simply ends the recording.

**Comment by ElBrad** [comment]
Could also be related to #44 maybe?

**Comment by HazCod** [comment]
Indeed, I think it’s because of #44. You can try building from the feat-ssdp branch and see if that fixes your issue.

**Comment by HazCod** [comment]
Closing since no feedback.
