### ISSUE TITLE
Allow baseURL to be overridden

### ISSUE THREAD

**Issue by OmgImAlexis** [tombowditch/telly#97]
I'm running this in a Docker swarm and currently the listening address is also the address used in the `/lineup.json` XML which seems to cause an issue playing as the stream URLs are then incorrect.

For example my main swarm's IP is 192.168.1.175 yet the json file lists URLs starting with `0.0.0.0` like this `http://0.0.0.0:6077/stream/`.

&nbsp;

The reason I can't use `--listen=192.168.1.175:6077` is that I'm using Docker swarm so telly can't bind to the host IP but could bind to `0.0.0.0` and use another URL/IP for the XML file.

**Comment by porkie02** [comment]
You can override it by assigning your container with its own ip. There is some exmaples here on how to do that. https://stackoverflow.com/questions/26539727/giving-a-docker-container-a-routable-ip-address

**Comment by porkie02** [comment]
You are a slightly irratating person.

**Comment by OmgImAlexis** [comment]
Instead of just answering the issue at hand you're walking me around in circles and treating me like I'm an idiot... how exactly didn't you think I would respond????

**Comment by HazCod** [comment]
Calm down folks. There is currently no code for getting the right interface IP.

**Comment by OmgImAlexis** [comment]
That's my whole point...
